#!../../../target/debug/ad-pylon-ioc
#============================================================
# st.cmd — ADPylon IOC for a Basler a2A1920-51gmBAS (GigE, mono)
#
# Usage:
#   cargo run -p ad-pylon-ioc -- iocs/ad/pylon-ioc/st.cmd
#============================================================

epicsEnvSet("PREFIX", "BAS1:")
epicsEnvSet("PORT",   "BAS1")
epicsEnvSet("XSIZE",  "1920")
epicsEnvSet("YSIZE",  "1200")
epicsEnvSet("NELEMENTS", "2304000")

# The CAMERA_ID can be either of the following:
#  Camera serial number
#  Camera index number, starting from 0
epicsEnvSet("CAMERA_ID", "40418973")

< $(ADPYLON)/st_base.cmd

# This camera model's GenICam features, generated by scripts/add_camera.sh.
dbLoadRecords("$(ADPYLON)/db/Basler-a2A1920-51gmBAS.template", "P=$(PREFIX),R=$(CAM),PORT=$(PORT)")
