//! The 266 parameters the driver adds to `ADDriver` (C `createParam`,
//! ADTimePix.cpp:1101-1411).
//!
//! Generated from the C header's `*String` macros and the `createParam` calls,
//! so every `drvInfo` string and asyn type matches the C driver exactly — the
//! db templates bind to these names.

use epics_rs::asyn::error::AsynResult;
use epics_rs::asyn::param::ParamType;
use epics_rs::asyn::port::PortDriverBase;

/// Parameter indices, in C's `createParam` order.
#[derive(Debug, Clone, Copy)]
pub struct TimePixParams {
    pub fw_time_stamp: usize,
    pub det_type: usize,
    pub http_code: usize,
    pub server_name: usize,
    pub det_connected: usize,
    pub serval_connected: usize,
    pub free_space: usize,
    pub write_speed: usize,
    pub lower_limit: usize,
    pub l_lim_reached: usize,
    pub local_temp: usize,
    pub fp_ga_temp: usize,
    pub fan1_speed: usize,
    pub fan2_speed: usize,
    pub bias_voltage: usize,
    pub humidity: usize,
    pub chip_temperature: usize,
    pub vd_d: usize,
    pub av_dd: usize,
    pub health: usize,
    pub iface_name: usize,
    pub sw_version: usize,
    pub fw_version: usize,
    pub pix_count: usize,
    pub row_len: usize,
    pub number_of_chips: usize,
    pub number_of_rows: usize,
    pub mpx_type: usize,
    pub boards_id: usize,
    pub boards_ip: usize,
    pub boards_ch1: usize,
    pub boards_ch2: usize,
    pub boards_ch3: usize,
    pub boards_ch4: usize,
    pub boards2_id: usize,
    pub boards2_ip: usize,
    pub boards_ch5: usize,
    pub boards_ch6: usize,
    pub boards_ch7: usize,
    pub boards_ch8: usize,
    pub supp_acq_modes: usize,
    pub clock_readout: usize,
    pub max_pulse_count: usize,
    pub max_pulse_height: usize,
    pub max_pulse_period: usize,
    pub timer_max_val: usize,
    pub timer_min_val: usize,
    pub timer_step: usize,
    pub clock_timepix: usize,
    pub fan1_pw_m: usize,
    pub fan2_pw_m: usize,
    pub bias_volt: usize,
    pub bias_enable: usize,
    pub chain_mode: usize,
    pub trigger_in: usize,
    pub trigger_out: usize,
    pub polarity: usize,
    pub trigger_mode: usize,
    pub exposure_time: usize,
    pub trigger_period: usize,
    pub n_triggers: usize,
    pub detector_orientation: usize,
    pub periph_clk80: usize,
    pub trigger_delay: usize,
    pub tdc: usize,
    pub tdc0: usize,
    pub tdc1: usize,
    pub global_timestamp_interval: usize,
    pub external_reference_clock: usize,
    pub log_level: usize,
    pub cp_pl_l: usize,
    pub disc_s1_of_f: usize,
    pub disc_s1_on: usize,
    pub disc_s2_of_f: usize,
    pub disc_s2_on: usize,
    pub ikrum: usize,
    pub pixel_da_c: usize,
    pub preamp_of_f: usize,
    pub preamp_on: usize,
    pub t_pbuffer_in: usize,
    pub t_pbuffer_out: usize,
    pub pl_l_vcntrl: usize,
    pub v_preamp_nc_as: usize,
    pub vt_pcoarse: usize,
    pub vt_pfine: usize,
    pub vfbk: usize,
    pub vthreshold_coarse: usize,
    pub vthreshold_fine: usize,
    pub adjust: usize,
    pub layout: usize,
    pub chip_n_temperature: usize,
    pub chip_nv_dd: usize,
    pub chip_na_vd_d: usize,
    pub bp_c_file_path: usize,
    pub bp_c_file_path_exists: usize,
    pub bp_c_file_name: usize,
    pub da_cs_file_path: usize,
    pub da_cs_file_path_exists: usize,
    pub da_cs_file_name: usize,
    pub write_msg: usize,
    pub write_bp_c_file: usize,
    pub write_da_cs_file: usize,
    pub write_data: usize,
    pub write_raw: usize,
    pub write_raw1: usize,
    pub write_img: usize,
    pub write_img1: usize,
    pub write_prv_img: usize,
    pub write_prv_img1: usize,
    pub write_prv_hst: usize,
    pub write_raw_read: usize,
    pub write_raw1_read: usize,
    pub write_img_read: usize,
    pub write_img1_read: usize,
    pub write_prv_img_read: usize,
    pub write_prv_img1_read: usize,
    pub write_prv_hst_read: usize,
    pub raw_base: usize,
    pub raw_file_pat: usize,
    pub raw_split_strategy: usize,
    pub raw_queue_size: usize,
    pub raw_file_path_exists: usize,
    pub raw1_base: usize,
    pub raw1_file_pat: usize,
    pub raw1_split_strategy: usize,
    pub raw1_queue_size: usize,
    pub raw1_file_path_exists: usize,
    pub img_base: usize,
    pub img_file_pat: usize,
    pub img_format: usize,
    pub img_mode: usize,
    pub img_ths: usize,
    pub img_int_size: usize,
    pub img_int_mode: usize,
    pub img_stp_on_dsk_lim: usize,
    pub img_queue_size: usize,
    pub img_file_path_exists: usize,
    pub img1_base: usize,
    pub img1_file_pat: usize,
    pub img1_format: usize,
    pub img1_mode: usize,
    pub img1_ths: usize,
    pub img1_int_size: usize,
    pub img1_int_mode: usize,
    pub img1_stp_on_dsk_lim: usize,
    pub img1_queue_size: usize,
    pub img1_file_path_exists: usize,
    pub prv_period: usize,
    pub prv_sampling_mode: usize,
    pub prv_img_base: usize,
    pub prv_img_file_pat: usize,
    pub prv_img_format: usize,
    pub prv_img_mode: usize,
    pub prv_img_ths: usize,
    pub prv_img_int_size: usize,
    pub prv_img_int_mode: usize,
    pub prv_img_stp_on_dsk_lim: usize,
    pub prv_img_queue_size: usize,
    pub prv_img_file_path_exists: usize,
    pub prv_img_frame_number: usize,
    pub prv_img_time_at_frame: usize,
    pub prv_img_acq_rate: usize,
    pub img_frame_number: usize,
    pub img_time_at_frame: usize,
    pub img_acq_rate: usize,
    pub img_image_data: usize,
    pub img_image_frame: usize,
    pub img_image_sum_n_frames: usize,
    pub img_accumulation_enable: usize,
    pub img_image_data_reset: usize,
    pub img_frames_to_sum: usize,
    pub img_sum_update_interval_frames: usize,
    pub img_total_counts: usize,
    pub img_processing_time: usize,
    pub img_memory_usage: usize,
    pub prv_img1_base: usize,
    pub prv_img1_file_pat: usize,
    pub prv_img1_format: usize,
    pub prv_img1_mode: usize,
    pub prv_img1_ths: usize,
    pub prv_img1_int_size: usize,
    pub prv_img1_int_mode: usize,
    pub prv_img1_stp_on_dsk_lim: usize,
    pub prv_img1_queue_size: usize,
    pub prv_img1_file_path_exists: usize,
    pub prv_hst_base: usize,
    pub prv_hst_file_pat: usize,
    pub prv_hst_format: usize,
    pub prv_hst_mode: usize,
    pub prv_hst_ths: usize,
    pub prv_hst_int_size: usize,
    pub prv_hst_int_mode: usize,
    pub prv_hst_stp_on_dsk_lim: usize,
    pub prv_hst_queue_size: usize,
    pub prv_hst_num_bins: usize,
    pub prv_hst_bin_width: usize,
    pub prv_hst_offset: usize,
    pub prv_hst_file_path_exists: usize,
    pub prv_hst_histogram_data: usize,
    pub prv_hst_histogram_frame: usize,
    pub prv_hst_histogram_sum_n_frames: usize,
    pub prv_hst_histogram_time_ms: usize,
    pub prv_hst_accumulation_enable: usize,
    pub prv_hst_time_at_frame: usize,
    pub prv_hst_frame_bin_size: usize,
    pub prv_hst_frame_bin_width: usize,
    pub prv_hst_frame_bin_offset: usize,
    pub prv_hst_frame_count: usize,
    pub prv_hst_total_counts: usize,
    pub prv_hst_acq_rate: usize,
    pub prv_hst_processing_time: usize,
    pub prv_hst_memory_usage: usize,
    pub prv_hst_frames_to_sum: usize,
    pub prv_hst_sum_update_interval: usize,
    pub prv_hst_data_reset: usize,
    pub pel_rate: usize,
    pub tdc1_rate: usize,
    pub tdc2_rate: usize,
    pub start_time: usize,
    pub elapsed_time: usize,
    pub time_left: usize,
    pub frame_count: usize,
    pub dropped_frames: usize,
    pub status: usize,
    pub stem_scan_width: usize,
    pub stem_scan_height: usize,
    pub stem_dwell_time: usize,
    pub stem_radius_outer: usize,
    pub stem_radius_inner: usize,
    pub tof_tdc_reference: usize,
    pub tof_min: usize,
    pub tof_max: usize,
    pub bp_c: usize,
    pub bp_cn: usize,
    pub bp_cmasked: usize,
    pub mask_bp_c: usize,
    pub mask_on_off_pel: usize,
    pub mask_reset: usize,
    pub mask_min_x: usize,
    pub mask_size_x: usize,
    pub mask_min_y: usize,
    pub mask_size_y: usize,
    pub mask_radius: usize,
    pub mask_rectangle: usize,
    pub mask_circle: usize,
    pub mask_file_name: usize,
    pub mask_pel: usize,
    pub mask_write: usize,
    pub raw_stream: usize,
    pub raw1_stream: usize,
    pub prv_hst_stream: usize,
    pub refresh_connection: usize,
    pub apply_config: usize,
    pub write_processed_img: usize,
    pub processed_img_output_type: usize,
    pub write_processed_hst: usize,
    pub processed_hst_output_type: usize,
    pub refresh_pixel_config: usize,
    pub pixel_config_len: usize,
    pub pixel_config_match_bp_c: usize,
    pub pixel_config_mismatch_bytes: usize,
    pub pixel_config_status: usize,
    pub pixel_config_diff: usize,
    pub masked_pels_json_path: usize,
    pub masked_pels_count: usize,
    pub masked_pels_export_status: usize,
}

impl TimePixParams {
    pub fn create(base: &mut PortDriverBase) -> AsynResult<Self> {
        use ParamType::*;
        Ok(Self {
            fw_time_stamp: base.create_param("TPX3_FW_TIMESTAMP", Octet)?,
            det_type: base.create_param("TPX3_DETECTOR_TYPE", Octet)?,
            http_code: base.create_param("TPX3_HTTP_CODE", Int32)?,
            server_name: base.create_param("TPX3_SERVER_NAME", Octet)?,
            det_connected: base.create_param("TPX3_DETECTOR_CONNECTED", Int32)?,
            serval_connected: base.create_param("TPX3_SERVAL_CONNECTED", Int32)?,
            free_space: base.create_param("TPX3_FREE_SPACE", Int64)?,
            write_speed: base.create_param("TPX3_WRITE_SPEED", Float64)?,
            lower_limit: base.create_param("TPX3_LLIM_SPACE", Int64)?,
            l_lim_reached: base.create_param("TPX3_LLIM_REACH", Int32)?,
            local_temp: base.create_param("TPX3_LOCAL_TEMP", Float64)?,
            fp_ga_temp: base.create_param("TPX3_FPGA_TEMP", Float64)?,
            fan1_speed: base.create_param("TPX3_FAN1_SPEED", Float64)?,
            fan2_speed: base.create_param("TPX3_FAN2_SPEED", Float64)?,
            bias_voltage: base.create_param("TPX3_BIAS_VOLT_H", Float64)?,
            humidity: base.create_param("TPX3_HUMIDITY", Int32)?,
            chip_temperature: base.create_param("TPX3_CHIP_TEMPS", Octet)?,
            vd_d: base.create_param("TPX3_VDD", Octet)?,
            av_dd: base.create_param("TPX3_AVDD", Octet)?,
            health: base.create_param("TPX3_HEALTH", Int32)?,
            iface_name: base.create_param("TPX3_IFACE", Octet)?,
            sw_version: base.create_param("TPX3_SW_VER", Octet)?,
            fw_version: base.create_param("TPX3_FW_VER", Octet)?,
            pix_count: base.create_param("TPX3_PEL_CNT", Int32)?,
            row_len: base.create_param("TPX3_ROWLEN", Int32)?,
            number_of_chips: base.create_param("TPX3_NUM_CHIPS", Int32)?,
            number_of_rows: base.create_param("TPX3_NUM_ROWS", Int32)?,
            mpx_type: base.create_param("TPX3_MPX_TYPE", Int32)?,
            boards_id: base.create_param("TPX3_BOARDS_ID", Octet)?,
            boards_ip: base.create_param("TPX3_BOARDS_IP", Octet)?,
            boards_ch1: base.create_param("TPX3_BOARDS_CH1", Octet)?,
            boards_ch2: base.create_param("TPX3_BOARDS_CH2", Octet)?,
            boards_ch3: base.create_param("TPX3_BOARDS_CH3", Octet)?,
            boards_ch4: base.create_param("TPX3_BOARDS_CH4", Octet)?,
            boards2_id: base.create_param("TPX3_BOARDS2_ID", Octet)?,
            boards2_ip: base.create_param("TPX3_BOARDS2_IP", Octet)?,
            boards_ch5: base.create_param("TPX3_BOARDS_CH5", Octet)?,
            boards_ch6: base.create_param("TPX3_BOARDS_CH6", Octet)?,
            boards_ch7: base.create_param("TPX3_BOARDS_CH7", Octet)?,
            boards_ch8: base.create_param("TPX3_BOARDS_CH8", Octet)?,
            supp_acq_modes: base.create_param("TPX3_ACQ_MODES", Int32)?,
            clock_readout: base.create_param("TPX3_CLOCK_READ", Float64)?,
            max_pulse_count: base.create_param("TPX3_PULSE_CNT", Int32)?,
            max_pulse_height: base.create_param("TPX3_PULSE_HEIGHT", Float64)?,
            max_pulse_period: base.create_param("TPX3_PULSE_PERIOD", Float64)?,
            timer_max_val: base.create_param("TPX3_TIME_MAX", Float64)?,
            timer_min_val: base.create_param("TPX3_TIME_MIN", Float64)?,
            timer_step: base.create_param("TPX3_TIME_STEP", Float64)?,
            clock_timepix: base.create_param("TPX3_CLOCK", Float64)?,
            fan1_pw_m: base.create_param("TPX3_FAN1PWM", Int32)?,
            fan2_pw_m: base.create_param("TPX3_FAN2PWM", Int32)?,
            bias_volt: base.create_param("TPX3_BIAS_VOLT_R", Int32)?,
            bias_enable: base.create_param("TPX3_BIAS_ENBL", Int32)?,
            chain_mode: base.create_param("TPX3_CHAIN_MODE", Int32)?,
            trigger_in: base.create_param("TPX3_TRIGGER_IN", Int32)?,
            trigger_out: base.create_param("TPX3_TRIGGER_OUT", Int32)?,
            polarity: base.create_param("TPX3_POLARITY", Int32)?,
            trigger_mode: base.create_param("TPX3_TRIGGER_MODE", Octet)?,
            exposure_time: base.create_param("TPX3_EXPOSURE_TIME", Float64)?,
            trigger_period: base.create_param("TPX3_TRIGGER_PERIOD", Float64)?,
            n_triggers: base.create_param("TPX3_NTRIGGERS", Int32)?,
            detector_orientation: base.create_param("TPX3_DET_ORIENTATION", Int32)?,
            periph_clk80: base.create_param("TPX3_PERIPH_CLK80", Int32)?,
            trigger_delay: base.create_param("TPX3_TRIG_DELAY", Float64)?,
            tdc: base.create_param("TPX3_TDC", Octet)?,
            tdc0: base.create_param("TPX3_TDC0", Int32)?,
            tdc1: base.create_param("TPX3_TDC1", Int32)?,
            global_timestamp_interval: base.create_param("TPX3_GL_TIMESTAMP_INT", Float64)?,
            external_reference_clock: base.create_param("TPX3_EXT_REF_CLOCK", Int32)?,
            log_level: base.create_param("TPX3_LOG_LEVEL", Int32)?,
            cp_pl_l: base.create_param("TPX3_CP_PLL", Int32)?,
            disc_s1_of_f: base.create_param("TPX3_DISCS1OFF", Int32)?,
            disc_s1_on: base.create_param("TPX3_DISCS1ON", Int32)?,
            disc_s2_of_f: base.create_param("TPX3_DISCS2OFF", Int32)?,
            disc_s2_on: base.create_param("TPX3_DISCS2ON", Int32)?,
            ikrum: base.create_param("TPX3_IKRUM", Int32)?,
            pixel_da_c: base.create_param("TPX3_PIXELDAC", Int32)?,
            preamp_of_f: base.create_param("TPX3_PREAMPOFF", Int32)?,
            preamp_on: base.create_param("TPX3_PREAMPON", Int32)?,
            t_pbuffer_in: base.create_param("TPX3_TPBUFFERIN", Int32)?,
            t_pbuffer_out: base.create_param("TPX3_TPBUFFEROUT", Int32)?,
            pl_l_vcntrl: base.create_param("TPX3_PLL_VCNTRL", Int32)?,
            v_preamp_nc_as: base.create_param("TPX3_VPREAMPNCAS", Int32)?,
            vt_pcoarse: base.create_param("TPX3_VTP_COARSE", Int32)?,
            vt_pfine: base.create_param("TPX3_VTP_FINE", Int32)?,
            vfbk: base.create_param("TPX3_VFBK", Int32)?,
            vthreshold_coarse: base.create_param("TPX3_VTH_COARSE", Int32)?,
            vthreshold_fine: base.create_param("TPX3_VTH_FINE", Int32)?,
            adjust: base.create_param("TPX3_ADJUST", Int32)?,
            layout: base.create_param("TPX3_LAYOUT", Octet)?,
            chip_n_temperature: base.create_param("TPX3_CHIP_TEMP", Int32)?,
            chip_nv_dd: base.create_param("TPX3_CHIP_VDD", Float64)?,
            chip_na_vd_d: base.create_param("TPX3_CHIP_AVDD", Float64)?,
            bp_c_file_path: base.create_param("BPC_FILE_PATH", Octet)?,
            bp_c_file_path_exists: base.create_param("BPC_FILE_PATH_EXISTS", Int32)?,
            bp_c_file_name: base.create_param("BPC_FILE_NAME", Octet)?,
            da_cs_file_path: base.create_param("DACS_FILE_PATH", Octet)?,
            da_cs_file_path_exists: base.create_param("DACS_FILE_PATH_EXISTS", Int32)?,
            da_cs_file_name: base.create_param("DACS_FILE_NAME", Octet)?,
            write_msg: base.create_param("WRITE_FILE_MESSAGE", Octet)?,
            write_bp_c_file: base.create_param("WRITE_BPC_FILE", Int32)?,
            write_da_cs_file: base.create_param("WRITE_DACS_FILE", Int32)?,
            write_data: base.create_param("TPX3_WRITE_DATA", Int32)?,
            write_raw: base.create_param("TPX3_WRITE_RAW", Int32)?,
            write_raw1: base.create_param("TPX3_WRITE_RAW1", Int32)?,
            write_img: base.create_param("TPX3_WRITE_IMG", Int32)?,
            write_img1: base.create_param("TPX3_WRITE_IMG1", Int32)?,
            write_prv_img: base.create_param("TPX3_WRITE_PRVIMG", Int32)?,
            write_prv_img1: base.create_param("TPX3_WRITE_PRVIMG1", Int32)?,
            write_prv_hst: base.create_param("TPX3_WRITE_PRVHST", Int32)?,
            write_raw_read: base.create_param("TPX3_WRITE_RAW_RBV", Int32)?,
            write_raw1_read: base.create_param("TPX3_WRITE_RAW1_RBV", Int32)?,
            write_img_read: base.create_param("TPX3_WRITE_IMG_RBV", Int32)?,
            write_img1_read: base.create_param("TPX3_WRITE_IMG1_RBV", Int32)?,
            write_prv_img_read: base.create_param("TPX3_WRITE_PRVIMG_RBV", Int32)?,
            write_prv_img1_read: base.create_param("TPX3_WRITE_PRVIMG1_RBV", Int32)?,
            write_prv_hst_read: base.create_param("TPX3_WRITE_PRVHST_RBV", Int32)?,
            raw_base: base.create_param("TPX3_RAW_BASE", Octet)?,
            raw_file_pat: base.create_param("TPX3_RAW_FILEPAT", Octet)?,
            raw_split_strategy: base.create_param("TPX3_RAW_SPLITSTG", Int32)?,
            raw_queue_size: base.create_param("TPX3_RAW_QUEUESIZE", Int32)?,
            raw_file_path_exists: base.create_param("RAW_FILE_PATH_EXISTS", Int32)?,
            raw1_base: base.create_param("TPX3_RAW1_BASE", Octet)?,
            raw1_file_pat: base.create_param("TPX3_RAW1_FILEPAT", Octet)?,
            raw1_split_strategy: base.create_param("TPX3_RAW1_SPLITSTG", Int32)?,
            raw1_queue_size: base.create_param("TPX3_RAW1_QUEUESIZE", Int32)?,
            raw1_file_path_exists: base.create_param("RAW1_FILE_PATH_EXISTS", Int32)?,
            img_base: base.create_param("TPX3_IMG_IMGBASE", Octet)?,
            img_file_pat: base.create_param("TPX3_IMG_IMGPAT", Octet)?,
            img_format: base.create_param("TPX3_IMG_IMGFORMAT", Int32)?,
            img_mode: base.create_param("TPX3_IMG_IMGMODE", Int32)?,
            img_ths: base.create_param("TPX3_IMG_IMGTHS", Octet)?,
            img_int_size: base.create_param("TPX3_IMG_INTSIZE", Int32)?,
            img_int_mode: base.create_param("TPX3_IMG_INTMODE", Int32)?,
            img_stp_on_dsk_lim: base.create_param("TPX3_IMG_STPONDSK", Int32)?,
            img_queue_size: base.create_param("TPX3_IMG_QUEUESIZE", Int32)?,
            img_file_path_exists: base.create_param("IMG_FILE_PATH_EXISTS", Int32)?,
            img1_base: base.create_param("TPX3_IMG_IMG1BASE", Octet)?,
            img1_file_pat: base.create_param("TPX3_IMG_IMG1PAT", Octet)?,
            img1_format: base.create_param("TPX3_IMG_IMG1FORMAT", Int32)?,
            img1_mode: base.create_param("TPX3_IMG_IMG1MODE", Int32)?,
            img1_ths: base.create_param("TPX3_IMG_IMG1THS", Octet)?,
            img1_int_size: base.create_param("TPX3_IMG_IMG1INTSIZE", Int32)?,
            img1_int_mode: base.create_param("TPX3_IMG_IMG1INTMODE", Int32)?,
            img1_stp_on_dsk_lim: base.create_param("TPX3_IMG_IMG1STPONDSK", Int32)?,
            img1_queue_size: base.create_param("TPX3_IMG_IMG1QUEUESIZE", Int32)?,
            img1_file_path_exists: base.create_param("IMG1_FILE_PATH_EXISTS", Int32)?,
            prv_period: base.create_param("TPX3_PRV_PERIOD", Float64)?,
            prv_sampling_mode: base.create_param("TPX3_PRV_SAMPLMODE", Int32)?,
            prv_img_base: base.create_param("TPX3_PRV_IMGBASE", Octet)?,
            prv_img_file_pat: base.create_param("TPX3_PRV_IMGPAT", Octet)?,
            prv_img_format: base.create_param("TPX3_PRV_IMGFORMAT", Int32)?,
            prv_img_mode: base.create_param("TPX3_PRV_IMGMODE", Int32)?,
            prv_img_ths: base.create_param("TPX3_PRV_IMGTHS", Octet)?,
            prv_img_int_size: base.create_param("TPX3_PRV_INTSIZE", Int32)?,
            prv_img_int_mode: base.create_param("TPX3_PRV_INTMODE", Int32)?,
            prv_img_stp_on_dsk_lim: base.create_param("TPX3_PRV_STPONDSK", Int32)?,
            prv_img_queue_size: base.create_param("TPX3_PRV_QUEUESIZE", Int32)?,
            prv_img_file_path_exists: base.create_param("PRV_IMG_FILE_PATH_EXISTS", Int32)?,
            prv_img_frame_number: base.create_param("TPX3_PRVIMG_FRAME_NUMBER", Int32)?,
            prv_img_time_at_frame: base.create_param("TPX3_PRVIMG_TIME_AT_FRAME", Float64)?,
            prv_img_acq_rate: base.create_param("TPX3_PRVIMG_ACQ_RATE", Float64)?,
            img_frame_number: base.create_param("TPX3_IMG_FRAME_NUMBER", Int32)?,
            img_time_at_frame: base.create_param("TPX3_IMG_TIME_AT_FRAME", Float64)?,
            img_acq_rate: base.create_param("TPX3_IMG_ACQ_RATE", Float64)?,
            img_image_data: base.create_param("TPX3_IMG_IMAGE_DATA", Int64Array)?,
            img_image_frame: base.create_param("TPX3_IMG_IMAGE_FRAME", Int32Array)?,
            img_image_sum_n_frames: base.create_param("TPX3_IMG_IMAGE_SUM_N_FRAMES", Int64Array)?,
            img_accumulation_enable: base.create_param("TPX3_IMG_ACCUMULATION_ENABLE", Int32)?,
            img_image_data_reset: base.create_param("TPX3_IMG_IMAGE_DATA_RESET", Int32)?,
            img_frames_to_sum: base.create_param("TPX3_IMG_FRAMES_TO_SUM", Int32)?,
            img_sum_update_interval_frames: base
                .create_param("TPX3_IMG_SUM_UPDATE_INTERVAL", Int32)?,
            img_total_counts: base.create_param("TPX3_IMG_TOTAL_COUNTS", Int64)?,
            img_processing_time: base.create_param("TPX3_IMG_PROCESSING_TIME", Float64)?,
            img_memory_usage: base.create_param("TPX3_IMG_MEMORY_USAGE", Float64)?,
            prv_img1_base: base.create_param("TPX3_PRV_IMG1BASE", Octet)?,
            prv_img1_file_pat: base.create_param("TPX3_PRV_IMG1PAT", Octet)?,
            prv_img1_format: base.create_param("TPX3_PRV_IMG1FORMAT", Int32)?,
            prv_img1_mode: base.create_param("TPX3_PRV_IMG1MODE", Int32)?,
            prv_img1_ths: base.create_param("TPX3_PRV_IMG1THS", Octet)?,
            prv_img1_int_size: base.create_param("TPX3_PRV_IMG1INTSIZE", Int32)?,
            prv_img1_int_mode: base.create_param("TPX3_PRV_IMG1INTMODE", Int32)?,
            prv_img1_stp_on_dsk_lim: base.create_param("TPX3_PRV_IMG1STPONDSK", Int32)?,
            prv_img1_queue_size: base.create_param("TPX3_PRV_IMG1QUEUESIZE", Int32)?,
            prv_img1_file_path_exists: base.create_param("PRV_IMG1_FILE_PATH_EXISTS", Int32)?,
            prv_hst_base: base.create_param("TPX3_PRV_HSTBASE", Octet)?,
            prv_hst_file_pat: base.create_param("TPX3_PRV_HSTPAT", Octet)?,
            prv_hst_format: base.create_param("TPX3_PRV_HSTFORMAT", Int32)?,
            prv_hst_mode: base.create_param("TPX3_PRV_HSTMODE", Int32)?,
            prv_hst_ths: base.create_param("TPX3_PRV_HSTTHS", Octet)?,
            prv_hst_int_size: base.create_param("TPX3_PRV_HSTINTSIZE", Int32)?,
            prv_hst_int_mode: base.create_param("TPX3_PRV_HSTINTMODE", Int32)?,
            prv_hst_stp_on_dsk_lim: base.create_param("TPX3_PRV_HSTSTPONDSK", Int32)?,
            prv_hst_queue_size: base.create_param("TPX3_PRV_HSTQUEUESIZE", Int32)?,
            prv_hst_num_bins: base.create_param("TPX3_PRV_HSTNBINS", Int32)?,
            prv_hst_bin_width: base.create_param("TPX3_PRV_HSTBINWIDTH", Float64)?,
            prv_hst_offset: base.create_param("TPX3_PRV_HSTOFFSET", Float64)?,
            prv_hst_file_path_exists: base.create_param("PRV_HST_FILE_PATH_EXISTS", Int32)?,
            prv_hst_histogram_data: base.create_param("TPX3_PRV_HST_HISTOGRAM_DATA", Int64Array)?,
            prv_hst_histogram_frame: base
                .create_param("TPX3_PRV_HST_HISTOGRAM_FRAME", Int32Array)?,
            prv_hst_histogram_sum_n_frames: base
                .create_param("TPX3_PRV_HST_HISTOGRAM_SUM_N_FRAMES", Int64Array)?,
            prv_hst_histogram_time_ms: base
                .create_param("TPX3_PRV_HST_HISTOGRAM_TIME_MS", Float64Array)?,
            prv_hst_accumulation_enable: base
                .create_param("TPX3_PRV_HST_ACCUMULATION_ENABLE", Int32)?,
            prv_hst_time_at_frame: base.create_param("TPX3_PRV_HST_TIME_AT_FRAME", Float64)?,
            prv_hst_frame_bin_size: base.create_param("TPX3_PRV_HST_FRAME_BIN_SIZE", Int32)?,
            prv_hst_frame_bin_width: base.create_param("TPX3_PRV_HST_FRAME_BIN_WIDTH", Int32)?,
            prv_hst_frame_bin_offset: base.create_param("TPX3_PRV_HST_FRAME_BIN_OFFSET", Int32)?,
            prv_hst_frame_count: base.create_param("TPX3_PRV_HST_FRAME_COUNT", Int32)?,
            prv_hst_total_counts: base.create_param("TPX3_PRV_HST_TOTAL_COUNTS", Int64)?,
            prv_hst_acq_rate: base.create_param("TPX3_PRV_HST_ACQ_RATE", Float64)?,
            prv_hst_processing_time: base.create_param("TPX3_PRV_HST_PROCESSING_TIME", Float64)?,
            prv_hst_memory_usage: base.create_param("TPX3_PRV_HST_MEMORY_USAGE", Float64)?,
            prv_hst_frames_to_sum: base.create_param("TPX3_PRV_HST_FRAMES_TO_SUM", Int32)?,
            prv_hst_sum_update_interval: base
                .create_param("TPX3_PRV_HST_SUM_UPDATE_INTERVAL", Int32)?,
            prv_hst_data_reset: base.create_param("TPX3_PRV_HST_DATA_RESET", Int32)?,
            pel_rate: base.create_param("TPX3_PEL_RATE", Int32)?,
            tdc1_rate: base.create_param("TPX3_TDC1_RATE", Int32)?,
            tdc2_rate: base.create_param("TPX3_TDC2_RATE", Int32)?,
            start_time: base.create_param("TPX3_START_TIME", Int64)?,
            elapsed_time: base.create_param("TPX3_ELAPSED_TIME", Float64)?,
            time_left: base.create_param("TPX3_TIME_LEFT", Float64)?,
            frame_count: base.create_param("TPX3_FRAME_COUNT", Int32)?,
            dropped_frames: base.create_param("TPX3_DROPPED_FRAMES", Int32)?,
            status: base.create_param("TPX3_MSMT_STATUS", Octet)?,
            stem_scan_width: base.create_param("TPX3_STEM_SCAN_WIDTH", Int32)?,
            stem_scan_height: base.create_param("TPX3_STEM_SCAN_HEIGHT", Int32)?,
            stem_dwell_time: base.create_param("TPX3_STEM_DWELL_TIME", Float64)?,
            stem_radius_outer: base.create_param("TPX3_STEM_RADIUS_OUTER", Int32)?,
            stem_radius_inner: base.create_param("TPX3_STEM_RADIUS_INNER", Int32)?,
            tof_tdc_reference: base.create_param("TPX3_TOF_TDC_REFERENCE", Octet)?,
            tof_min: base.create_param("TPX3_TOF_MIN", Float64)?,
            tof_max: base.create_param("TPX3_TOF_MAX", Float64)?,
            bp_c: base.create_param("TPX3_BPC_PEL", Int32)?,
            bp_cn: base.create_param("TPX3_BPC_PEL_N", Int32)?,
            bp_cmasked: base.create_param("TPX3_BPC_PEL_MASKED", Int32)?,
            mask_bp_c: base.create_param("TPX3_MASK_ARRAY_BPC", Int32)?,
            mask_on_off_pel: base.create_param("TPX3_MASK_ONOFF_PEL", Int32)?,
            mask_reset: base.create_param("TPX3_MASK_RESET", Int32)?,
            mask_min_x: base.create_param("TPX3_MASK_MINX", Int32)?,
            mask_size_x: base.create_param("TPX3_MASK_SIZEX", Int32)?,
            mask_min_y: base.create_param("TPX3_MASK_MINY", Int32)?,
            mask_size_y: base.create_param("TPX3_MASK_SIZEY", Int32)?,
            mask_radius: base.create_param("TPX3_MASK_RADIUS", Int32)?,
            mask_rectangle: base.create_param("TPX3_MASK_RECTANGLE", Int32)?,
            mask_circle: base.create_param("TPX3_MASK_CIRCLE", Int32)?,
            mask_file_name: base.create_param("TPX3_MASK_FILENAME", Octet)?,
            mask_pel: base.create_param("TPX3_MASK_PEL", Int32)?,
            mask_write: base.create_param("TPX3_MASK_WRITE", Int32)?,
            raw_stream: base.create_param("TPX3_RAW_STREAM", Int32)?,
            raw1_stream: base.create_param("TPX3_RAW1_STREAM", Int32)?,
            prv_hst_stream: base.create_param("TPX3_PRV_HST_STREAM", Int32)?,
            refresh_connection: base.create_param("TPX3_REFRESH_CONNECTION", Int32)?,
            apply_config: base.create_param("TPX3_APPLY_CONFIG", Int32)?,
            write_processed_img: base.create_param("TPX3_IMG_WRITE_PROCESSED", Int32)?,
            processed_img_output_type: base
                .create_param("TPX3_IMG_PROCESSED_OUTPUT_TYPE", Int32)?,
            write_processed_hst: base.create_param("TPX3_HST_WRITE_PROCESSED", Int32)?,
            processed_hst_output_type: base
                .create_param("TPX3_HST_PROCESSED_OUTPUT_TYPE", Int32)?,
            refresh_pixel_config: base.create_param("TPX3_REFRESH_PIXEL_CONFIG", Int32)?,
            pixel_config_len: base.create_param("TPX3_PIXEL_CONFIG_LEN", Int32)?,
            pixel_config_match_bp_c: base.create_param("TPX3_PIXEL_CONFIG_MATCH_BPC", Int32)?,
            pixel_config_mismatch_bytes: base.create_param("TPX3_PIXEL_CONFIG_MISMATCH", Int64)?,
            pixel_config_status: base.create_param("TPX3_PIXEL_CONFIG_STATUS", Octet)?,
            pixel_config_diff: base.create_param("TPX3_PIXEL_CONFIG_DIFF", Int32Array)?,
            masked_pels_json_path: base.create_param("TPX3_MASKED_PELS_JSON_RBV", Octet)?,
            masked_pels_count: base.create_param("TPX3_MASKED_PELS_COUNT_RBV", Int32)?,
            masked_pels_export_status: base
                .create_param("TPX3_MASKED_PELS_EXPORT_STATUS_RBV", Octet)?,
        })
    }
}

/// Every `drvInfo` this driver creates, in `create` order — the db templates
/// bind to these names.
pub const DRV_INFO: [&str; 266] = [
    "TPX3_FW_TIMESTAMP",
    "TPX3_DETECTOR_TYPE",
    "TPX3_HTTP_CODE",
    "TPX3_SERVER_NAME",
    "TPX3_DETECTOR_CONNECTED",
    "TPX3_SERVAL_CONNECTED",
    "TPX3_FREE_SPACE",
    "TPX3_WRITE_SPEED",
    "TPX3_LLIM_SPACE",
    "TPX3_LLIM_REACH",
    "TPX3_LOCAL_TEMP",
    "TPX3_FPGA_TEMP",
    "TPX3_FAN1_SPEED",
    "TPX3_FAN2_SPEED",
    "TPX3_BIAS_VOLT_H",
    "TPX3_HUMIDITY",
    "TPX3_CHIP_TEMPS",
    "TPX3_VDD",
    "TPX3_AVDD",
    "TPX3_HEALTH",
    "TPX3_IFACE",
    "TPX3_SW_VER",
    "TPX3_FW_VER",
    "TPX3_PEL_CNT",
    "TPX3_ROWLEN",
    "TPX3_NUM_CHIPS",
    "TPX3_NUM_ROWS",
    "TPX3_MPX_TYPE",
    "TPX3_BOARDS_ID",
    "TPX3_BOARDS_IP",
    "TPX3_BOARDS_CH1",
    "TPX3_BOARDS_CH2",
    "TPX3_BOARDS_CH3",
    "TPX3_BOARDS_CH4",
    "TPX3_BOARDS2_ID",
    "TPX3_BOARDS2_IP",
    "TPX3_BOARDS_CH5",
    "TPX3_BOARDS_CH6",
    "TPX3_BOARDS_CH7",
    "TPX3_BOARDS_CH8",
    "TPX3_ACQ_MODES",
    "TPX3_CLOCK_READ",
    "TPX3_PULSE_CNT",
    "TPX3_PULSE_HEIGHT",
    "TPX3_PULSE_PERIOD",
    "TPX3_TIME_MAX",
    "TPX3_TIME_MIN",
    "TPX3_TIME_STEP",
    "TPX3_CLOCK",
    "TPX3_FAN1PWM",
    "TPX3_FAN2PWM",
    "TPX3_BIAS_VOLT_R",
    "TPX3_BIAS_ENBL",
    "TPX3_CHAIN_MODE",
    "TPX3_TRIGGER_IN",
    "TPX3_TRIGGER_OUT",
    "TPX3_POLARITY",
    "TPX3_TRIGGER_MODE",
    "TPX3_EXPOSURE_TIME",
    "TPX3_TRIGGER_PERIOD",
    "TPX3_NTRIGGERS",
    "TPX3_DET_ORIENTATION",
    "TPX3_PERIPH_CLK80",
    "TPX3_TRIG_DELAY",
    "TPX3_TDC",
    "TPX3_TDC0",
    "TPX3_TDC1",
    "TPX3_GL_TIMESTAMP_INT",
    "TPX3_EXT_REF_CLOCK",
    "TPX3_LOG_LEVEL",
    "TPX3_CP_PLL",
    "TPX3_DISCS1OFF",
    "TPX3_DISCS1ON",
    "TPX3_DISCS2OFF",
    "TPX3_DISCS2ON",
    "TPX3_IKRUM",
    "TPX3_PIXELDAC",
    "TPX3_PREAMPOFF",
    "TPX3_PREAMPON",
    "TPX3_TPBUFFERIN",
    "TPX3_TPBUFFEROUT",
    "TPX3_PLL_VCNTRL",
    "TPX3_VPREAMPNCAS",
    "TPX3_VTP_COARSE",
    "TPX3_VTP_FINE",
    "TPX3_VFBK",
    "TPX3_VTH_COARSE",
    "TPX3_VTH_FINE",
    "TPX3_ADJUST",
    "TPX3_LAYOUT",
    "TPX3_CHIP_TEMP",
    "TPX3_CHIP_VDD",
    "TPX3_CHIP_AVDD",
    "BPC_FILE_PATH",
    "BPC_FILE_PATH_EXISTS",
    "BPC_FILE_NAME",
    "DACS_FILE_PATH",
    "DACS_FILE_PATH_EXISTS",
    "DACS_FILE_NAME",
    "WRITE_FILE_MESSAGE",
    "WRITE_BPC_FILE",
    "WRITE_DACS_FILE",
    "TPX3_WRITE_DATA",
    "TPX3_WRITE_RAW",
    "TPX3_WRITE_RAW1",
    "TPX3_WRITE_IMG",
    "TPX3_WRITE_IMG1",
    "TPX3_WRITE_PRVIMG",
    "TPX3_WRITE_PRVIMG1",
    "TPX3_WRITE_PRVHST",
    "TPX3_WRITE_RAW_RBV",
    "TPX3_WRITE_RAW1_RBV",
    "TPX3_WRITE_IMG_RBV",
    "TPX3_WRITE_IMG1_RBV",
    "TPX3_WRITE_PRVIMG_RBV",
    "TPX3_WRITE_PRVIMG1_RBV",
    "TPX3_WRITE_PRVHST_RBV",
    "TPX3_RAW_BASE",
    "TPX3_RAW_FILEPAT",
    "TPX3_RAW_SPLITSTG",
    "TPX3_RAW_QUEUESIZE",
    "RAW_FILE_PATH_EXISTS",
    "TPX3_RAW1_BASE",
    "TPX3_RAW1_FILEPAT",
    "TPX3_RAW1_SPLITSTG",
    "TPX3_RAW1_QUEUESIZE",
    "RAW1_FILE_PATH_EXISTS",
    "TPX3_IMG_IMGBASE",
    "TPX3_IMG_IMGPAT",
    "TPX3_IMG_IMGFORMAT",
    "TPX3_IMG_IMGMODE",
    "TPX3_IMG_IMGTHS",
    "TPX3_IMG_INTSIZE",
    "TPX3_IMG_INTMODE",
    "TPX3_IMG_STPONDSK",
    "TPX3_IMG_QUEUESIZE",
    "IMG_FILE_PATH_EXISTS",
    "TPX3_IMG_IMG1BASE",
    "TPX3_IMG_IMG1PAT",
    "TPX3_IMG_IMG1FORMAT",
    "TPX3_IMG_IMG1MODE",
    "TPX3_IMG_IMG1THS",
    "TPX3_IMG_IMG1INTSIZE",
    "TPX3_IMG_IMG1INTMODE",
    "TPX3_IMG_IMG1STPONDSK",
    "TPX3_IMG_IMG1QUEUESIZE",
    "IMG1_FILE_PATH_EXISTS",
    "TPX3_PRV_PERIOD",
    "TPX3_PRV_SAMPLMODE",
    "TPX3_PRV_IMGBASE",
    "TPX3_PRV_IMGPAT",
    "TPX3_PRV_IMGFORMAT",
    "TPX3_PRV_IMGMODE",
    "TPX3_PRV_IMGTHS",
    "TPX3_PRV_INTSIZE",
    "TPX3_PRV_INTMODE",
    "TPX3_PRV_STPONDSK",
    "TPX3_PRV_QUEUESIZE",
    "PRV_IMG_FILE_PATH_EXISTS",
    "TPX3_PRVIMG_FRAME_NUMBER",
    "TPX3_PRVIMG_TIME_AT_FRAME",
    "TPX3_PRVIMG_ACQ_RATE",
    "TPX3_IMG_FRAME_NUMBER",
    "TPX3_IMG_TIME_AT_FRAME",
    "TPX3_IMG_ACQ_RATE",
    "TPX3_IMG_IMAGE_DATA",
    "TPX3_IMG_IMAGE_FRAME",
    "TPX3_IMG_IMAGE_SUM_N_FRAMES",
    "TPX3_IMG_ACCUMULATION_ENABLE",
    "TPX3_IMG_IMAGE_DATA_RESET",
    "TPX3_IMG_FRAMES_TO_SUM",
    "TPX3_IMG_SUM_UPDATE_INTERVAL",
    "TPX3_IMG_TOTAL_COUNTS",
    "TPX3_IMG_PROCESSING_TIME",
    "TPX3_IMG_MEMORY_USAGE",
    "TPX3_PRV_IMG1BASE",
    "TPX3_PRV_IMG1PAT",
    "TPX3_PRV_IMG1FORMAT",
    "TPX3_PRV_IMG1MODE",
    "TPX3_PRV_IMG1THS",
    "TPX3_PRV_IMG1INTSIZE",
    "TPX3_PRV_IMG1INTMODE",
    "TPX3_PRV_IMG1STPONDSK",
    "TPX3_PRV_IMG1QUEUESIZE",
    "PRV_IMG1_FILE_PATH_EXISTS",
    "TPX3_PRV_HSTBASE",
    "TPX3_PRV_HSTPAT",
    "TPX3_PRV_HSTFORMAT",
    "TPX3_PRV_HSTMODE",
    "TPX3_PRV_HSTTHS",
    "TPX3_PRV_HSTINTSIZE",
    "TPX3_PRV_HSTINTMODE",
    "TPX3_PRV_HSTSTPONDSK",
    "TPX3_PRV_HSTQUEUESIZE",
    "TPX3_PRV_HSTNBINS",
    "TPX3_PRV_HSTBINWIDTH",
    "TPX3_PRV_HSTOFFSET",
    "PRV_HST_FILE_PATH_EXISTS",
    "TPX3_PRV_HST_HISTOGRAM_DATA",
    "TPX3_PRV_HST_HISTOGRAM_FRAME",
    "TPX3_PRV_HST_HISTOGRAM_SUM_N_FRAMES",
    "TPX3_PRV_HST_HISTOGRAM_TIME_MS",
    "TPX3_PRV_HST_ACCUMULATION_ENABLE",
    "TPX3_PRV_HST_TIME_AT_FRAME",
    "TPX3_PRV_HST_FRAME_BIN_SIZE",
    "TPX3_PRV_HST_FRAME_BIN_WIDTH",
    "TPX3_PRV_HST_FRAME_BIN_OFFSET",
    "TPX3_PRV_HST_FRAME_COUNT",
    "TPX3_PRV_HST_TOTAL_COUNTS",
    "TPX3_PRV_HST_ACQ_RATE",
    "TPX3_PRV_HST_PROCESSING_TIME",
    "TPX3_PRV_HST_MEMORY_USAGE",
    "TPX3_PRV_HST_FRAMES_TO_SUM",
    "TPX3_PRV_HST_SUM_UPDATE_INTERVAL",
    "TPX3_PRV_HST_DATA_RESET",
    "TPX3_PEL_RATE",
    "TPX3_TDC1_RATE",
    "TPX3_TDC2_RATE",
    "TPX3_START_TIME",
    "TPX3_ELAPSED_TIME",
    "TPX3_TIME_LEFT",
    "TPX3_FRAME_COUNT",
    "TPX3_DROPPED_FRAMES",
    "TPX3_MSMT_STATUS",
    "TPX3_STEM_SCAN_WIDTH",
    "TPX3_STEM_SCAN_HEIGHT",
    "TPX3_STEM_DWELL_TIME",
    "TPX3_STEM_RADIUS_OUTER",
    "TPX3_STEM_RADIUS_INNER",
    "TPX3_TOF_TDC_REFERENCE",
    "TPX3_TOF_MIN",
    "TPX3_TOF_MAX",
    "TPX3_BPC_PEL",
    "TPX3_BPC_PEL_N",
    "TPX3_BPC_PEL_MASKED",
    "TPX3_MASK_ARRAY_BPC",
    "TPX3_MASK_ONOFF_PEL",
    "TPX3_MASK_RESET",
    "TPX3_MASK_MINX",
    "TPX3_MASK_SIZEX",
    "TPX3_MASK_MINY",
    "TPX3_MASK_SIZEY",
    "TPX3_MASK_RADIUS",
    "TPX3_MASK_RECTANGLE",
    "TPX3_MASK_CIRCLE",
    "TPX3_MASK_FILENAME",
    "TPX3_MASK_PEL",
    "TPX3_MASK_WRITE",
    "TPX3_RAW_STREAM",
    "TPX3_RAW1_STREAM",
    "TPX3_PRV_HST_STREAM",
    "TPX3_REFRESH_CONNECTION",
    "TPX3_APPLY_CONFIG",
    "TPX3_IMG_WRITE_PROCESSED",
    "TPX3_IMG_PROCESSED_OUTPUT_TYPE",
    "TPX3_HST_WRITE_PROCESSED",
    "TPX3_HST_PROCESSED_OUTPUT_TYPE",
    "TPX3_REFRESH_PIXEL_CONFIG",
    "TPX3_PIXEL_CONFIG_LEN",
    "TPX3_PIXEL_CONFIG_MATCH_BPC",
    "TPX3_PIXEL_CONFIG_MISMATCH",
    "TPX3_PIXEL_CONFIG_STATUS",
    "TPX3_PIXEL_CONFIG_DIFF",
    "TPX3_MASKED_PELS_JSON_RBV",
    "TPX3_MASKED_PELS_COUNT_RBV",
    "TPX3_MASKED_PELS_EXPORT_STATUS_RBV",
];
