#============================================================
# st.cmd -- SyringePump IOC startup script
#
# Usage:
#   cargo run -p syringepump-ioc -- st.cmd
#
# Wires all three pump families from epics-modules/SyringePump:
#   - Teledyne ISCO D/H-series (native asyn port driver -- drivers/syringepump)
#   - ISCO (Modbus/TCP, drvModbusAsynConfigure)
#   - Vindum (Modbus RTU-over-TCP, drvModbusAsynConfigure)
# No upstream st.cmd/iocBoot ships for either Teledyne family (confirmed
# absent from epics-modules/SyringePump/iocBoot) -- the wiring below is a
# demo instantiation of each, chosen by this port, not sourced from an
# upstream reference. ISCO/Vindum's drvModbusAsynConfigure arguments below
# ARE sourced verbatim from the real upstream
# iocBoot/iocISCO/st.cmd and iocBoot/iocVindum/st.cmd.
#
# Deviation: dbLoadTemplate is not an iocsh command in epics-base-rs 0.22.1
# (see src/main.rs's module doc for the full rationale). Every ISCO*/Vindum*
# .substitutions row below is mechanically expanded into one explicit
# dbLoadRecords call -- textually equivalent to what dbLoadTemplate would
# have produced. Each block below cites the exact upstream .substitutions
# file it was expanded from.
#
# Omitted (matching drivers/love, drivers/scaler974, motor/amci precedent
# in this workspace): autosave/save_restore machinery
# (create_monitor_set/auto_settings.req) and the optional debug asynRecord
# instance upstream's st.cmd loads. Neither is protocol logic.
#============================================================

epicsEnvSet("P", "SP:")

# ------------------------------------------------------------------
# Teledyne D-series (demo instance -- no upstream st.cmd/iocBoot exists
# for either Teledyne family; see header comment).
# ------------------------------------------------------------------
# The driver port records bind to ($(TELD_PORT)) must differ from the serial
# transport it rides on ($(TELD_TTY)): TeledyneDInit registers its own port,
# so reusing the serial port's name collides ("port already registered").
epicsEnvSet("TELD_PORT", "TelD1")
epicsEnvSet("TELD_TTY", "TelD1_tty")
drvAsynSerialPortConfigure("$(TELD_TTY)", "/dev/ttyS0", 0, 0, 0)
asynSetTraceIOMask("$(TELD_TTY)", 0, HEX)
# TeledyneDInit(port, serPort, serAddr, unit) -- unit 6 matches
# teled_d.proto/teled_h.proto's shipped default ($(u=6), never overridden
# anywhere upstream).
TeledyneDInit("$(TELD_PORT)", "$(TELD_TTY)", 0, 6)

dbLoadRecords("db/teledynePumpD.template", "P=$(P),PUMP=D1:,s=SP,ta=Teledyne,ss=D1,PORT=$(TELD_PORT),ADDR=0")

# ------------------------------------------------------------------
# Teledyne H-series (demo instance -- see header comment).
# ------------------------------------------------------------------
epicsEnvSet("TELH_PORT", "TelH1")
epicsEnvSet("TELH_TTY", "TelH1_tty")
drvAsynSerialPortConfigure("$(TELH_TTY)", "/dev/ttyS1", 0, 0, 0)
asynSetTraceIOMask("$(TELH_TTY)", 0, HEX)
TeledyneHInit("$(TELH_PORT)", "$(TELH_TTY)", 0, 6)

dbLoadRecords("db/teledynePumpH.template", "s=SP,ta=Teledyne,ss=H1,PORT=$(TELH_PORT)")

# ------------------------------------------------------------------
# ISCO -- wiring and drvModbusAsynConfigure arguments taken verbatim from
# the real upstream epics-modules/SyringePump/iocBoot/iocISCO/st.cmd.
# ------------------------------------------------------------------
epicsEnvSet("PREFIX", "ISCO1:")
epicsEnvSet("ISCO_PORT", "SP1")
epicsEnvSet("POLL_MS", "1000")
epicsEnvSet("TIMEOUT_MS", "2000")

drvAsynIPPortConfigure("$(ISCO_PORT)", "gse-isco1:502", 0, 0, 0)
asynSetTraceIOMask("$(ISCO_PORT)", 0, HEX)
asynSetTraceIOTruncateSize("$(ISCO_PORT)", 0, 256)
modbusInterposeConfig("$(ISCO_PORT)", 0, $(TIMEOUT_MS), 0)

# Access 142 bits (0-141) as inputs. Function code=1.
drvModbusAsynConfigure("$(ISCO_PORT)_Bit_In",  "$(ISCO_PORT)", 1, 1,  0, 142, 0, $(POLL_MS), "Teledyne")
# Access 109 bits (0-108) as outputs. Function code=5.
drvModbusAsynConfigure("$(ISCO_PORT)_Bit_Out", "$(ISCO_PORT)", 1, 5,  0, 109, 0, 1, "Teledyne")
# Access first set of 100 16-bit holding registers starting at 0 as inputs. Function code=3. Data type=FLOAT32_BE
drvModbusAsynConfigure("$(ISCO_PORT)_Reg_In_1",  "$(ISCO_PORT)", 1,  3, 0, 100, FLOAT32_BE, $(POLL_MS), "Teledyne")
# Access second set of 62 16-bit holding registers starting at 100 as inputs. Function code=3. Data type=FLOAT32_BE
drvModbusAsynConfigure("$(ISCO_PORT)_Reg_In_2",  "$(ISCO_PORT)", 1,  3, 100, 62, FLOAT32_BE, $(POLL_MS), "Teledyne")
# Access third set of 46 16-bit holding registers starting at 200 as inputs. Function code=3. Data type=FLOAT32_BE
drvModbusAsynConfigure("$(ISCO_PORT)_Reg_In_3",  "$(ISCO_PORT)", 1,  3, 200, 46, FLOAT32_BE, $(POLL_MS), "Teledyne")
# Access first set of 100 16-bit holding registers starting at 0 as outputs. Function code=16. Data type=FLOAT32_BE
drvModbusAsynConfigure("$(ISCO_PORT)_Reg_Out_1",  "$(ISCO_PORT)", 1,  16, 0, 100, FLOAT32_BE, 1, "Teledyne")
# Access second set of 62 16-bit holding registers starting at 100 as outputs. Function code=16. Data type=FLOAT32_BE
drvModbusAsynConfigure("$(ISCO_PORT)_Reg_Out_2",  "$(ISCO_PORT)", 1,  16, 100, 62, FLOAT32_BE, 1, "Teledyne")

# Load the substitutions files for the records that use Modbus (expanded --
# see this file's header comment). Order matches upstream st.cmd exactly.

# Expanded from epics-modules/SyringePump/SPApp/Db/ISCOBinaryIn.substitutions
# --- file "$(MODBUS)/db/bi_bit.template" --- (142 rows)
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:Run_RBV,PORT=SP1_Bit_In,OFFSET=0,ZNAM=Stopped,ONAM=Running,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:Run_RBV,PORT=SP1_Bit_In,OFFSET=1,ZNAM=Stopped,ONAM=Running,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:Run_RBV,PORT=SP1_Bit_In,OFFSET=2,ZNAM=Stopped,ONAM=Running,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:Run_RBV,PORT=SP1_Bit_In,OFFSET=3,ZNAM=Stopped,ONAM=Running,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=Link-AB-CD_RBV,PORT=SP1_Bit_In,OFFSET=4,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:Refill_RBV,PORT=SP1_Bit_In,OFFSET=5,ZNAM=Stop,ONAM=Run,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:Refill_RBV,PORT=SP1_Bit_In,OFFSET=6,ZNAM=Stop,ONAM=Run,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:Refill_RBV,PORT=SP1_Bit_In,OFFSET=7,ZNAM=Stop,ONAM=Run,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:Refill_RBV,PORT=SP1_Bit_In,OFFSET=8,ZNAM=Stop,ONAM=Run,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:ConstPress_RBV,PORT=SP1_Bit_In,OFFSET=9,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:ConstPress_RBV,PORT=SP1_Bit_In,OFFSET=10,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:ConstPress_RBV,PORT=SP1_Bit_In,OFFSET=11,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:ConstPress_RBV,PORT=SP1_Bit_In,OFFSET=12,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:ConstFlow_RBV,PORT=SP1_Bit_In,OFFSET=13,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:ConstFlow_RBV,PORT=SP1_Bit_In,OFFSET=14,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:ConstFlow_RBV,PORT=SP1_Bit_In,OFFSET=15,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:ConstFlow_RBV,PORT=SP1_Bit_In,OFFSET=16,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:Independent_RBV,PORT=SP1_Bit_In,OFFSET=17,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:ConstFlow_RBV,PORT=SP1_Bit_In,OFFSET=18,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:ConstPress_RBV,PORT=SP1_Bit_In,OFFSET=19,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:ModAdd_RBV,PORT=SP1_Bit_In,OFFSET=20,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:ContModAdd_RBV,PORT=SP1_Bit_In,OFFSET=21,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=CD:Independent_RBV,PORT=SP1_Bit_In,OFFSET=22,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=CD:ConstFlow_RBV,PORT=SP1_Bit_In,OFFSET=23,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=CD:ConstPress_RBV,PORT=SP1_Bit_In,OFFSET=24,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:DeliverMode_RBV,PORT=SP1_Bit_In,OFFSET=25,ZNAM=Deliver,ONAM=Receive,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:PressureMode_RBV,PORT=SP1_Bit_In,OFFSET=26,ZNAM=Low,ONAM=Normal,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:PressureMatch_RBV,PORT=SP1_Bit_In,OFFSET=27,ZNAM=Fast,ONAM=Normal,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=CD:DeliverMode_RBV,PORT=SP1_Bit_In,OFFSET=28,ZNAM=Deliver,ONAM=Receive,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=CD:PressureMode_RBV,PORT=SP1_Bit_In,OFFSET=29,ZNAM=Low,ONAM=Normal,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=CD:PressureMatch_RBV,PORT=SP1_Bit_In,OFFSET=30,ZNAM=Fast,ONAM=Normal,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:RapidPress_RBV,PORT=SP1_Bit_In,OFFSET=31,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:RapidPress_RBV,PORT=SP1_Bit_In,OFFSET=32,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:RapidPress_RBV,PORT=SP1_Bit_In,OFFSET=33,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:RapidPress_RBV,PORT=SP1_Bit_In,OFFSET=34,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:Equilibrating_RBV,PORT=SP1_Bit_In,OFFSET=35,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:Equilibrating_RBV,PORT=SP1_Bit_In,OFFSET=36,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:Equilibrating_RBV,PORT=SP1_Bit_In,OFFSET=37,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:Equilibrating_RBV,PORT=SP1_Bit_In,OFFSET=38,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:InHold_RBV,PORT=SP1_Bit_In,OFFSET=39,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:InHold_RBV,PORT=SP1_Bit_In,OFFSET=40,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:InHold_RBV,PORT=SP1_Bit_In,OFFSET=41,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:InHold_RBV,PORT=SP1_Bit_In,OFFSET=42,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:ConcGradient_RBV,PORT=SP1_Bit_In,OFFSET=43,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:PressGradient_RBV,PORT=SP1_Bit_In,OFFSET=44,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:FlowGradient_RBV,PORT=SP1_Bit_In,OFFSET=45,ZNAM=False,ONAM=True,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=LocalOperation_RBV,PORT=SP1_Bit_In,OFFSET=46,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=NO_ALARM,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=RemoteOperation_RBV,PORT=SP1_Bit_In,OFFSET=47,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=ExternalOperation_RBV,PORT=SP1_Bit_In,OFFSET=48,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=ExternalRefill_RBV,PORT=SP1_Bit_In,OFFSET=49,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:ZeroPressure_RBV,PORT=SP1_Bit_In,OFFSET=50,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:ZeroPressure_RBV,PORT=SP1_Bit_In,OFFSET=51,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:ZeroPressure_RBV,PORT=SP1_Bit_In,OFFSET=52,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:ZeroPressure_RBV,PORT=SP1_Bit_In,OFFSET=53,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:PressIntegrator_RBV,PORT=SP1_Bit_In,OFFSET=54,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:PressIntegrator_RBV,PORT=SP1_Bit_In,OFFSET=55,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:PressIntegrator_RBV,PORT=SP1_Bit_In,OFFSET=56,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:PressIntegrator_RBV,PORT=SP1_Bit_In,OFFSET=57,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:PressDeadband_RBV,PORT=SP1_Bit_In,OFFSET=58,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:PressDeadband_RBV,PORT=SP1_Bit_In,OFFSET=59,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:PressDeadband_RBV,PORT=SP1_Bit_In,OFFSET=60,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:PressDeadband_RBV,PORT=SP1_Bit_In,OFFSET=61,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:AutoRefill_RBV,PORT=SP1_Bit_In,OFFSET=62,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:AutoRefill_RBV,PORT=SP1_Bit_In,OFFSET=63,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:AutoRefill_RBV,PORT=SP1_Bit_In,OFFSET=64,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:AutoRefill_RBV,PORT=SP1_Bit_In,OFFSET=65,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:AutoFill_RBV,PORT=SP1_Bit_In,OFFSET=66,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:AutoFill_RBV,PORT=SP1_Bit_In,OFFSET=67,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:AutoFill_RBV,PORT=SP1_Bit_In,OFFSET=68,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:AutoFill_RBV,PORT=SP1_Bit_In,OFFSET=69,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OutputBit1_RBV,PORT=SP1_Bit_In,OFFSET=70,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OutputBit2_RBV,PORT=SP1_Bit_In,OFFSET=71,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OutputBit3_RBV,PORT=SP1_Bit_In,OFFSET=72,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OutputBit4_RBV,PORT=SP1_Bit_In,OFFSET=73,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OutputBit5_RBV,PORT=SP1_Bit_In,OFFSET=74,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OutputBit6_RBV,PORT=SP1_Bit_In,OFFSET=75,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OutputBit7_RBV,PORT=SP1_Bit_In,OFFSET=76,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OutputBit8_RBV,PORT=SP1_Bit_In,OFFSET=77,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:DispenseModeCF_RBV,PORT=SP1_Bit_In,OFFSET=78,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:DispenseModeCF_RBV,PORT=SP1_Bit_In,OFFSET=79,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:DispenseModeCF_RBV,PORT=SP1_Bit_In,OFFSET=80,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:DispenseModeCF_RBV,PORT=SP1_Bit_In,OFFSET=81,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:ResetVolDel_RBV,PORT=SP1_Bit_In,OFFSET=82,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=AB:ResetVolDel_RBV,PORT=SP1_Bit_In,OFFSET=83,ZNAM=Disabled,ONAM=Enabled,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=Unit:ATM_RBV,PORT=SP1_Bit_In,OFFSET=84,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=Unit:BAR_RBV,PORT=SP1_Bit_In,OFFSET=85,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=Unit:kPa_RBV,PORT=SP1_Bit_In,OFFSET=86,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=Unit:PSI_RBV,PORT=SP1_Bit_In,OFFSET=87,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=Unit:mlPerMin_RBV,PORT=SP1_Bit_In,OFFSET=88,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=Unit:mlPerHr_RBV,PORT=SP1_Bit_In,OFFSET=89,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=Unit:ulPerMin_RBV,PORT=SP1_Bit_In,OFFSET=90,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=Unit:ulPerHr_RBV,PORT=SP1_Bit_In,OFFSET=91,ZNAM=Off,ONAM=On,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OverpressAlarm_RBV,PORT=SP1_Bit_In,OFFSET=92,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OverpressDisplay_RBV,PORT=SP1_Bit_In,OFFSET=93,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OverpressShutdown_RBV,PORT=SP1_Bit_In,OFFSET=94,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=UnderpressAlarm_RBV,PORT=SP1_Bit_In,OFFSET=95,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=UnderpressDisplay_RBV,PORT=SP1_Bit_In,OFFSET=96,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=UnderpressShutdown_RBV,PORT=SP1_Bit_In,OFFSET=97,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OverflowAlarm_RBV,PORT=SP1_Bit_In,OFFSET=98,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OverflowDisplay_RBV,PORT=SP1_Bit_In,OFFSET=99,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=OverflowShutdown_RBV,PORT=SP1_Bit_In,OFFSET=100,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=UnderflowAlarm_RBV,PORT=SP1_Bit_In,OFFSET=101,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=UnderflowDisplay_RBV,PORT=SP1_Bit_In,OFFSET=102,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=UnderflowShutdown_RBV,PORT=SP1_Bit_In,OFFSET=103,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:PoorFillAlarm_RBV,PORT=SP1_Bit_In,OFFSET=104,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:PoorFillAlarm_RBV,PORT=SP1_Bit_In,OFFSET=105,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:PoorFillAlarm_RBV,PORT=SP1_Bit_In,OFFSET=106,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:PoorFillAlarm_RBV,PORT=SP1_Bit_In,OFFSET=107,ZNAM=Disable,ONAM=Enable,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=ResetAll_RBV,PORT=SP1_Bit_In,OFFSET=108,ZNAM=Done,ONAM=Reset,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:Transducer_RBV,PORT=SP1_Bit_In,OFFSET=109,ZNAM=Disconnected,ONAM=Connected,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:Empty_RBV,PORT=SP1_Bit_In,OFFSET=110,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:Full_RBV,PORT=SP1_Bit_In,OFFSET=111,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:Overpressure_RBV,PORT=SP1_Bit_In,OFFSET=112,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:Underpressure_RBV,PORT=SP1_Bit_In,OFFSET=113,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:MotorFailure_RBV,PORT=SP1_Bit_In,OFFSET=114,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:Transducer_RBV,PORT=SP1_Bit_In,OFFSET=115,ZNAM=Disconnected,ONAM=Connected,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:Empty_RBV,PORT=SP1_Bit_In,OFFSET=116,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:Full_RBV,PORT=SP1_Bit_In,OFFSET=117,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:Overpressure_RBV,PORT=SP1_Bit_In,OFFSET=118,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:Underpressure_RBV,PORT=SP1_Bit_In,OFFSET=119,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:MotorFailure_RBV,PORT=SP1_Bit_In,OFFSET=120,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:Transducer_RBV,PORT=SP1_Bit_In,OFFSET=121,ZNAM=Disconnected,ONAM=Connected,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:Empty_RBV,PORT=SP1_Bit_In,OFFSET=122,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:Full_RBV,PORT=SP1_Bit_In,OFFSET=123,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:Overpressure_RBV,PORT=SP1_Bit_In,OFFSET=124,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:Underpressure_RBV,PORT=SP1_Bit_In,OFFSET=125,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:MotorFailure_RBV,PORT=SP1_Bit_In,OFFSET=126,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:Transducer_RBV,PORT=SP1_Bit_In,OFFSET=127,ZNAM=Disconnected,ONAM=Connected,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:Empty_RBV,PORT=SP1_Bit_In,OFFSET=128,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:Full_RBV,PORT=SP1_Bit_In,OFFSET=129,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:Overpressure_RBV,PORT=SP1_Bit_In,OFFSET=130,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:Underpressure_RBV,PORT=SP1_Bit_In,OFFSET=131,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:MotorFailure_RBV,PORT=SP1_Bit_In,OFFSET=132,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=A:PoorFill_RBV,PORT=SP1_Bit_In,OFFSET=133,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=B:PoorFill_RBV,PORT=SP1_Bit_In,OFFSET=134,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=C:PoorFill_RBV,PORT=SP1_Bit_In,OFFSET=135,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=D:PoorFill_RBV,PORT=SP1_Bit_In,OFFSET=136,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=ValveError_RBV,PORT=SP1_Bit_In,OFFSET=137,ZNAM=OK,ONAM=Fault,ZSV=NO_ALARM,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=InputBit1_RBV,PORT=SP1_Bit_In,OFFSET=138,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=InputBit2_RBV,PORT=SP1_Bit_In,OFFSET=139,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=InputBit3_RBV,PORT=SP1_Bit_In,OFFSET=140,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(PREFIX),R=InputBit4_RBV,PORT=SP1_Bit_In,OFFSET=141,ZNAM=Low,ONAM=High,ZSV=NO_ALARM,OSV=MINOR,SCAN=\"I/O Intr\"")

# Expanded from epics-modules/SyringePump/SPApp/Db/ISCOBinaryOut.substitutions
# --- file "$(MODBUS)/db/bo_bit.template" --- (98 rows)
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:Run,PORT=SP1_Bit_Out,OFFSET=0,ZNAM=Stop,ONAM=Run")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:Run,PORT=SP1_Bit_Out,OFFSET=1,ZNAM=Stop,ONAM=Run")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:Run,PORT=SP1_Bit_Out,OFFSET=2,ZNAM=Stop,ONAM=Run")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:Run,PORT=SP1_Bit_Out,OFFSET=3,ZNAM=Stop,ONAM=Run")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=Link-AB-CD,PORT=SP1_Bit_Out,OFFSET=4,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:Refill,PORT=SP1_Bit_Out,OFFSET=5,ZNAM=Stop,ONAM=Run")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:Refill,PORT=SP1_Bit_Out,OFFSET=6,ZNAM=Stop,ONAM=Run")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:Refill,PORT=SP1_Bit_Out,OFFSET=7,ZNAM=Stop,ONAM=Run")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:Refill,PORT=SP1_Bit_Out,OFFSET=8,ZNAM=Stop,ONAM=Run")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:ConstPress,PORT=SP1_Bit_Out,OFFSET=9,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:ConstPress,PORT=SP1_Bit_Out,OFFSET=10,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:ConstPress,PORT=SP1_Bit_Out,OFFSET=11,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:ConstPress,PORT=SP1_Bit_Out,OFFSET=12,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:ConstFlow,PORT=SP1_Bit_Out,OFFSET=13,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:ConstFlow,PORT=SP1_Bit_Out,OFFSET=14,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:ConstFlow,PORT=SP1_Bit_Out,OFFSET=15,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:ConstFlow,PORT=SP1_Bit_Out,OFFSET=16,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=AB:Independent,PORT=SP1_Bit_Out,OFFSET=17,ZNAM=False,ONAM=True")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=AB:ConstFlow,PORT=SP1_Bit_Out,OFFSET=18,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=AB:ConstPress,PORT=SP1_Bit_Out,OFFSET=19,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=AB:ModAdd,PORT=SP1_Bit_Out,OFFSET=20,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=AB:ContModAdd,PORT=SP1_Bit_Out,OFFSET=21,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=CD:Independent,PORT=SP1_Bit_Out,OFFSET=22,ZNAM=False,ONAM=True")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=CD:ConstFlow,PORT=SP1_Bit_Out,OFFSET=23,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=CD:ConstPress,PORT=SP1_Bit_Out,OFFSET=24,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=AB:DeliverMode,PORT=SP1_Bit_Out,OFFSET=25,ZNAM=Deliver,ONAM=Receive")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=AB:PressureMode,PORT=SP1_Bit_Out,OFFSET=26,ZNAM=Low,ONAM=Normal")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=AB:PressureMatch,PORT=SP1_Bit_Out,OFFSET=27,ZNAM=Fast,ONAM=Normal")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=CD:DeliverMode,PORT=SP1_Bit_Out,OFFSET=28,ZNAM=Deliver,ONAM=Receive")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=CD:PressureMode,PORT=SP1_Bit_Out,OFFSET=29,ZNAM=Low,ONAM=Normal")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=CD:PressureMatch,PORT=SP1_Bit_Out,OFFSET=30,ZNAM=Fast,ONAM=Normal")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:RapidPress,PORT=SP1_Bit_Out,OFFSET=31,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:RapidPress,PORT=SP1_Bit_Out,OFFSET=32,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:RapidPress,PORT=SP1_Bit_Out,OFFSET=33,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:RapidPress,PORT=SP1_Bit_Out,OFFSET=34,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=LocalOperation,PORT=SP1_Bit_Out,OFFSET=46,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=RemoteOperation,PORT=SP1_Bit_Out,OFFSET=47,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=ExternalOperation,PORT=SP1_Bit_Out,OFFSET=48,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=ExternalRefill,PORT=SP1_Bit_Out,OFFSET=49,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:ZeroPressure,PORT=SP1_Bit_Out,OFFSET=50,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:ZeroPressure,PORT=SP1_Bit_Out,OFFSET=51,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:ZeroPressure,PORT=SP1_Bit_Out,OFFSET=52,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:ZeroPressure,PORT=SP1_Bit_Out,OFFSET=53,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:PressIntegrator,PORT=SP1_Bit_Out,OFFSET=54,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:PressIntegrator,PORT=SP1_Bit_Out,OFFSET=55,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:PressIntegrator,PORT=SP1_Bit_Out,OFFSET=56,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:PressIntegrator,PORT=SP1_Bit_Out,OFFSET=57,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:PressDeadband8,PORT=SP1_Bit_Out,OFFSET=58,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:PressDeadband,PORT=SP1_Bit_Out,OFFSET=59,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:PressDeadband,PORT=SP1_Bit_Out,OFFSET=60,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:PressDeadband,PORT=SP1_Bit_Out,OFFSET=61,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:AutoRefill,PORT=SP1_Bit_Out,OFFSET=62,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:AutoRefill,PORT=SP1_Bit_Out,OFFSET=63,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:AutoRefill,PORT=SP1_Bit_Out,OFFSET=64,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:AutoRefill,PORT=SP1_Bit_Out,OFFSET=65,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:AutoFill,PORT=SP1_Bit_Out,OFFSET=66,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:AutoFill,PORT=SP1_Bit_Out,OFFSET=67,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:AutoFill,PORT=SP1_Bit_Out,OFFSET=68,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:AutoFill,PORT=SP1_Bit_Out,OFFSET=69,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OutputBit1,PORT=SP1_Bit_Out,OFFSET=70,ZNAM=Low,ONAM=High")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OutputBit2,PORT=SP1_Bit_Out,OFFSET=71,ZNAM=Low,ONAM=High")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OutputBit3,PORT=SP1_Bit_Out,OFFSET=72,ZNAM=Low,ONAM=High")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OutputBit4,PORT=SP1_Bit_Out,OFFSET=73,ZNAM=Low,ONAM=High")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OutputBit5,PORT=SP1_Bit_Out,OFFSET=74,ZNAM=Low,ONAM=High")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OutputBit6,PORT=SP1_Bit_Out,OFFSET=75,ZNAM=Low,ONAM=High")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OutputBit7,PORT=SP1_Bit_Out,OFFSET=76,ZNAM=Low,ONAM=High")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OutputBit8,PORT=SP1_Bit_Out,OFFSET=77,ZNAM=Low,ONAM=High")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:DispenseModeCF,PORT=SP1_Bit_Out,OFFSET=78,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:DispenseModeCF,PORT=SP1_Bit_Out,OFFSET=79,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:DispenseModeCF,PORT=SP1_Bit_Out,OFFSET=80,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:DispenseModeCF,PORT=SP1_Bit_Out,OFFSET=81,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=AB:ResetVolDel,PORT=SP1_Bit_Out,OFFSET=82,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=CD:ResetVolDel,PORT=SP1_Bit_Out,OFFSET=83,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=Unit:ATM,PORT=SP1_Bit_Out,OFFSET=84,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=Unit:BAR,PORT=SP1_Bit_Out,OFFSET=85,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=Unit:kPa,PORT=SP1_Bit_Out,OFFSET=86,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=Unit:PSI,PORT=SP1_Bit_Out,OFFSET=87,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=Unit:mlPerMin,PORT=SP1_Bit_Out,OFFSET=88,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=Unit:mlPerHr,PORT=SP1_Bit_Out,OFFSET=89,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=Unit:ulPerMin,PORT=SP1_Bit_Out,OFFSET=90,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=Unit:ulPerHr,PORT=SP1_Bit_Out,OFFSET=91,ZNAM=Off,ONAM=On")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OverpressAlarm,PORT=SP1_Bit_Out,OFFSET=92,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OverpressDisplay,PORT=SP1_Bit_Out,OFFSET=93,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OverpressShutdown,PORT=SP1_Bit_Out,OFFSET=94,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=UnderpressAlarm,PORT=SP1_Bit_Out,OFFSET=95,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=UnderpressDisplay,PORT=SP1_Bit_Out,OFFSET=96,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=UnderpressShutdown,PORT=SP1_Bit_Out,OFFSET=97,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OverflowAlarm,PORT=SP1_Bit_Out,OFFSET=98,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OverflowDisplay,PORT=SP1_Bit_Out,OFFSET=99,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=OverflowShutdown,PORT=SP1_Bit_Out,OFFSET=100,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=UnderflowAlarm,PORT=SP1_Bit_Out,OFFSET=101,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=UnderflowDisplay,PORT=SP1_Bit_Out,OFFSET=102,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=UnderflowShutdown,PORT=SP1_Bit_Out,OFFSET=103,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=A:PoorFillAlarm,PORT=SP1_Bit_Out,OFFSET=104,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=B:PoorFillAlarm,PORT=SP1_Bit_Out,OFFSET=105,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=C:PoorFillAlarm,PORT=SP1_Bit_Out,OFFSET=106,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=D:PoorFillAlarm,PORT=SP1_Bit_Out,OFFSET=107,ZNAM=Disable,ONAM=Enable")
dbLoadRecords("db/bo_bit.template", "P=$(PREFIX),R=ResetAll,PORT=SP1_Bit_Out,OFFSET=108,ZNAM=Done,ONAM=Reset")

# Expanded from epics-modules/SyringePump/SPApp/Db/ISCOAnalogIn.substitutions
# (row "D:RefillRateSP_RBV" -- Fixed, upstream defect, unambiguous
# in-file target: ISCOAnalogIn.substitutions:20 is missing the comma
# between the R and PORT columns present on every sibling A/B/C row;
# repaired here, matching the A/B/C pattern.)
# --- file "$(MODBUS)/db/aiFloat64.template" --- (104 rows)
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:PressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=0,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:PressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=2,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:PressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=4,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:PressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=6,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=AB:PressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=8,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=CD:PressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=10,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:FlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=12,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:FlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=14,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:FlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=16,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:FlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=18,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=AB:FlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=20,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=CD:FlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=22,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:RefillRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=24,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:RefillRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=26,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:RefillRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=28,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:RefillRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=30,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:MaxPressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=32,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:MaxPressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=34,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:MaxPressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=36,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:MaxPressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=38,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:MinPressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=40,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:MinPressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=42,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:MinPressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=44,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:MinPressureSP_RBV,PORT=SP1_Reg_In_1,OFFSET=46,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:MaxFlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=48,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:MaxFlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=50,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:MaxFlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=52,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:MaxFlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=54,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:MinFlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=56,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:MinFlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=58,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:MinFlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=60,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:MinFlowRateSP_RBV,PORT=SP1_Reg_In_1,OFFSET=62,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:MaxFlowLimit_RBV,PORT=SP1_Reg_In_1,OFFSET=64,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:MaxFlowLimit_RBV,PORT=SP1_Reg_In_1,OFFSET=66,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:MaxFlowLimit_RBV,PORT=SP1_Reg_In_1,OFFSET=68,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:MaxFlowLimit_RBV,PORT=SP1_Reg_In_1,OFFSET=70,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:Pressure_RBV,PORT=SP1_Reg_In_1,OFFSET=72,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:FlowRate_RBV,PORT=SP1_Reg_In_1,OFFSET=74,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:VolumeRemaining_RBV,PORT=SP1_Reg_In_1,OFFSET=76,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:Pressure_RBV,PORT=SP1_Reg_In_1,OFFSET=78,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:FlowRate_RBV,PORT=SP1_Reg_In_1,OFFSET=80,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:VolumeRemaining_RBV,PORT=SP1_Reg_In_1,OFFSET=82,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:Pressure_RBV,PORT=SP1_Reg_In_1,OFFSET=84,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:FlowRate_RBV,PORT=SP1_Reg_In_1,OFFSET=86,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:VolumeRemaining_RBV,PORT=SP1_Reg_In_1,OFFSET=88,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:Pressure_RBV,PORT=SP1_Reg_In_1,OFFSET=90,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:FlowRate_RBV,PORT=SP1_Reg_In_1,OFFSET=92,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:VolumeRemaining_RBV,PORT=SP1_Reg_In_1,OFFSET=94,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=AB:FlowRate_RBV,PORT=SP1_Reg_In_1,OFFSET=96,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=AB:Pressure_RBV,PORT=SP1_Reg_In_1,OFFSET=98,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=AB:VolumeDelivered_RBV,PORT=SP1_Reg_In_2,OFFSET=0,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=CD:Pressure_RBV,PORT=SP1_Reg_In_2,OFFSET=2,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=CD:FlowRate_RBV,PORT=SP1_Reg_In_2,OFFSET=4,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=CD:VolumeDelivered_RBV,PORT=SP1_Reg_In_2,OFFSET=6,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=VoltageIn1_RBV,PORT=SP1_Reg_In_2,OFFSET=8,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=VoltageIn2_RBV,PORT=SP1_Reg_In_2,OFFSET=10,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=VoltageIn3_RBV,PORT=SP1_Reg_In_2,OFFSET=12,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=VoltageIn4_RBV,PORT=SP1_Reg_In_2,OFFSET=14,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:RefillAtVolume_RBV,PORT=SP1_Reg_In_2,OFFSET=16,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:RefillAtVolume_RBVV,PORT=SP1_Reg_In_2,OFFSET=18,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:RefillAtVolume_RBV,PORT=SP1_Reg_In_2,OFFSET=20,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:RefillAtVolume_RBV,PORT=SP1_Reg_In_2,OFFSET=22,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:RefillToVolume_RBV,PORT=SP1_Reg_In_2,OFFSET=24,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:RefillToVolume_RBV,PORT=SP1_Reg_In_2,OFFSET=26,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:RefillToVolume_RBV,PORT=SP1_Reg_In_2,OFFSET=28,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:RefillToVolume_RBV,PORT=SP1_Reg_In_2,OFFSET=30,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=AB:RefillToPercent_RBV,PORT=SP1_Reg_In_2,OFFSET=32,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=AB:DeliverToPercent_RBV,PORT=SP1_Reg_In_2,OFFSET=34,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=CD:RefillToPercent_RBV,PORT=SP1_Reg_In_2,OFFSET=36,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=CD:DeliverToPercent_RBV,PORT=SP1_Reg_In_2,OFFSET=38,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:PoorFillMark_RBV,PORT=SP1_Reg_In_2,OFFSET=40,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:PoorFillMark_RBV,PORT=SP1_Reg_In_2,OFFSET=42,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:PoorFillMark_RBV,PORT=SP1_Reg_In_2,OFFSET=44,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:PoorFillMark_RBV,PORT=SP1_Reg_In_2,OFFSET=46,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:VolumeDispensed_RBV,PORT=SP1_Reg_In_2,OFFSET=48,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:VolumeDispensed_RBV,PORT=SP1_Reg_In_2,OFFSET=50,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:VolumeDispensed_RBV,PORT=SP1_Reg_In_2,OFFSET=52,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:VolumeDispensed_RBV,PORT=SP1_Reg_In_2,OFFSET=54,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=reg:156_RBV,PORT=SP1_Reg_In_2,OFFSET=56,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=reg:158_RBV,PORT=SP1_Reg_In_2,OFFSET=58,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=reg:160_RBV,PORT=SP1_Reg_In_2,OFFSET=60,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:AbsMaxPressure_RBV,PORT=SP1_Reg_In_3,OFFSET=0,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:AbsMaxFlowRate_RBV,PORT=SP1_Reg_In_3,OFFSET=2,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:AbsMaxRefillRate_RBV,PORT=SP1_Reg_In_3,OFFSET=4,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:MaxVolume_RBV,PORT=SP1_Reg_In_3,OFFSET=6,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:AbsMaxPressure_RBV,PORT=SP1_Reg_In_3,OFFSET=8,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:AbsMaxFlowRate_RBV,PORT=SP1_Reg_In_3,OFFSET=10,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:AbsMaxRefillRate_RBV,PORT=SP1_Reg_In_3,OFFSET=12,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:MaxVolume_RBV,PORT=SP1_Reg_In_3,OFFSET=14,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:AbsMaxPressure_RBV,PORT=SP1_Reg_In_3,OFFSET=16,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:AbsMaxFlowRate_RBV,PORT=SP1_Reg_In_3,OFFSET=18,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:AbsMaxRefillRate_RBV,PORT=SP1_Reg_In_3,OFFSET=20,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:MaxVolume_RBV,PORT=SP1_Reg_In_3,OFFSET=22,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:AbsMaxPressure_RBV,PORT=SP1_Reg_In_3,OFFSET=24,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:AbsMaxFlowRate_RBV,PORT=SP1_Reg_In_3,OFFSET=26,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:AbsMaxRefillRate_RBV,PORT=SP1_Reg_In_3,OFFSET=28,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:MaxVolume_RBV,PORT=SP1_Reg_In_3,OFFSET=30,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=A:PumpType_RBV,PORT=SP1_Reg_In_3,OFFSET=32,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=B:PumpType_RBV,PORT=SP1_Reg_In_3,OFFSET=34,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=C:PumpType_RBV,PORT=SP1_Reg_In_3,OFFSET=36,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=D:PumpType_RBV,PORT=SP1_Reg_In_3,OFFSET=38,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=SoftwareMajor_RBV,PORT=SP1_Reg_In_3,OFFSET=40,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=SoftwareMinor_RBV,PORT=SP1_Reg_In_3,OFFSET=42,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aiFloat64.template", "P=$(PREFIX),R=SoftwareMicro_RBV,PORT=SP1_Reg_In_3,OFFSET=44,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")

# Expanded from epics-modules/SyringePump/SPApp/Db/ISCOAnalogOut.substitutions
# --- file "$(MODBUS)/db/aoFloat64.template" --- (59 rows)
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:PressureSP,PORT=SP1_Reg_Out_1,OFFSET=0,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:PressureSP,PORT=SP1_Reg_Out_1,OFFSET=2,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:PressureSP,PORT=SP1_Reg_Out_1,OFFSET=4,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:PressureSP,PORT=SP1_Reg_Out_1,OFFSET=6,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=AB:PressureSP,PORT=SP1_Reg_Out_1,OFFSET=8,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=CD:PressureSP,PORT=SP1_Reg_Out_1,OFFSET=10,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:FlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=12,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:FlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=14,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:FlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=16,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:FlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=18,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=AB:FlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=20,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=CD:FlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=22,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:RefillRateSP,PORT=SP1_Reg_Out_1,OFFSET=24,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:RefillRateSP,PORT=SP1_Reg_Out_1,OFFSET=26,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:RefillRateSP,PORT=SP1_Reg_Out_1,OFFSET=28,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:RefillRateSP,PORT=SP1_Reg_Out_1,OFFSET=30,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:MaxPressureSP,PORT=SP1_Reg_Out_1,OFFSET=32,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:MaxPressureSP,PORT=SP1_Reg_Out_1,OFFSET=34,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:MaxPressureSP,PORT=SP1_Reg_Out_1,OFFSET=36,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:MaxPressureSP,PORT=SP1_Reg_Out_1,OFFSET=38,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:MinPressureSP,PORT=SP1_Reg_Out_1,OFFSET=40,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:MinPressureSP,PORT=SP1_Reg_Out_1,OFFSET=42,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:MinPressureSP,PORT=SP1_Reg_Out_1,OFFSET=44,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:MinPressureSP,PORT=SP1_Reg_Out_1,OFFSET=46,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:MaxFlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=48,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:MaxFlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=50,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:MaxFlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=52,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:MaxFlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=54,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:MinFlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=56,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:MinFlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=58,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:MinFlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=60,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:MinFlowRateSP,PORT=SP1_Reg_Out_1,OFFSET=62,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:MaxFlowLimit,PORT=SP1_Reg_Out_1,OFFSET=64,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:MaxFlowLimit,PORT=SP1_Reg_Out_1,OFFSET=66,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:MaxFlowLimit,PORT=SP1_Reg_Out_1,OFFSET=68,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:MaxFlowLimit,PORT=SP1_Reg_Out_1,OFFSET=70,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:RefillAtVolume,PORT=SP1_Reg_Out_2,OFFSET=16,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:RefillAtVolume,PORT=SP1_Reg_Out_2,OFFSET=18,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:RefillAtVolume,PORT=SP1_Reg_Out_2,OFFSET=20,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:RefillAtVolume,PORT=SP1_Reg_Out_2,OFFSET=22,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:RefillToVolume,PORT=SP1_Reg_Out_2,OFFSET=24,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:RefillToVolume,PORT=SP1_Reg_Out_2,OFFSET=26,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:RefillToVolume,PORT=SP1_Reg_Out_2,OFFSET=28,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:RefillToVolume,PORT=SP1_Reg_Out_2,OFFSET=30,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=AB:RefillToPercent,PORT=SP1_Reg_Out_2,OFFSET=32,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=AB:DeliverToPercent,PORT=SP1_Reg_Out_2,OFFSET=34,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=CD:RefillToPercent,PORT=SP1_Reg_Out_2,OFFSET=36,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=CD:DeliverToPercent,PORT=SP1_Reg_Out_2,OFFSET=38,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:PoorFillMark,PORT=SP1_Reg_Out_2,OFFSET=40,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:PoorFillMark,PORT=SP1_Reg_Out_2,OFFSET=42,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:PoorFillMark,PORT=SP1_Reg_Out_2,OFFSET=44,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:PoorFillMark,PORT=SP1_Reg_Out_2,OFFSET=46,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=A:VolumeDispensed,PORT=SP1_Reg_Out_2,OFFSET=48,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=B:VolumeDispensed,PORT=SP1_Reg_Out_2,OFFSET=50,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=C:VolumeDispensed,PORT=SP1_Reg_Out_2,OFFSET=52,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=D:VolumeDispensed,PORT=SP1_Reg_Out_2,OFFSET=54,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=reg:156,PORT=SP1_Reg_Out_2,OFFSET=56,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=reg:158,PORT=SP1_Reg_Out_2,OFFSET=58,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")
dbLoadRecords("db/aoFloat64.template", "P=$(PREFIX),R=reg:160,PORT=SP1_Reg_Out_2,OFFSET=60,DATA_TYPE=FLOAT32_BE,LOPR=0,HOPR=10,PREC=4,EGU=egu,SCAN=\"I/O Intr\",DESC=Register")

# Load a database with other records for the controller
dbLoadRecords("db/ISCOController.template", "P=$(PREFIX)")

# Load a database with other records for each pump (A, B, AB only --
# matching upstream's own commented-out C/D/CD instantiations)
dbLoadRecords("db/ISCOPumpN.template", "P=$(PREFIX), PUMP=A:")
dbLoadRecords("db/ISCOPumpN.template", "P=$(PREFIX), PUMP=B:")
#dbLoadRecords("db/ISCOPumpN.template", "P=$(PREFIX), PUMP=C:")
#dbLoadRecords("db/ISCOPumpN.template", "P=$(PREFIX), PUMP=D:")
dbLoadRecords("db/ISCOPumpN.template", "P=$(PREFIX), PUMP=AB:")
#dbLoadRecords("db/ISCOPumpN.template", "P=$(PREFIX), PUMP=CD:")

# ------------------------------------------------------------------
# Vindum -- wiring and drvModbusAsynConfigure arguments taken verbatim
# from the real upstream epics-modules/SyringePump/iocBoot/iocVindum/st.cmd.
# modbusInterposeConfig linkType=1 (RTU) matches upstream: the VP pump
# is Modbus RTU framing carried over a TCP terminal-server link, not
# native Modbus/TCP (upstream's own st.cmd comments this distinction).
# VPREFIX/VINDUM_PORT/VPOLL_MS/VTIMEOUT_MS (rather than upstream's
# PREFIX/PORT/POLL_MS/TIMEOUT_MS) avoid clobbering the ISCO section's
# same-named macros above, since both families are wired in one st.cmd.
# ------------------------------------------------------------------
epicsEnvSet("VPREFIX", "VINDUM1:P1:")
epicsEnvSet("VINDUM_PORT", "SP2")
epicsEnvSet("VPOLL_MS", "100")
epicsEnvSet("VTIMEOUT_MS", "2000")

# This is for a Digi One SP in TCP sockets mode (matching upstream).
drvAsynIPPortConfigure("$(VINDUM_PORT)", "gsets22:4002", 0, 0, 0)
asynSetTraceIOMask("$(VINDUM_PORT)", 0, HEX)
asynSetTraceMask("$(VINDUM_PORT)", 0, ERROR|DRIVER)
asynSetTraceIOTruncateSize("$(VINDUM_PORT)", 0, 256)
modbusInterposeConfig("$(VINDUM_PORT)", 1, $(VTIMEOUT_MS), 0)

# Read 31 bits starting at address 0. Function code=1. Default data type=UINT16
drvModbusAsynConfigure("$(VINDUM_PORT)_ReadCoils", "$(VINDUM_PORT)", 1, 1, 0, 31, UINT16, $(VPOLL_MS), "Vindum")
# Expanded from epics-modules/SyringePump/SPApp/Db/VindumReadCoils.substitutions
# --- file "$(MODBUS)/db/bi_bit.template" --- (6 rows)
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadCoils,R=A:FillValve_RBV,OFFSET=0,ZNAM=Closed,ZSV=NO_ALARM,ONAM=Open,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadCoils,R=A:DeliverValve_RBV,OFFSET=1,ZNAM=Closed,ZSV=NO_ALARM,ONAM=Open,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadCoils,R=B:FillValve_RBV,OFFSET=2,ZNAM=Closed,ZSV=NO_ALARM,ONAM=Open,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadCoils,R=B:DeliverValve_RBV,OFFSET=3,ZNAM=Closed,ZSV=NO_ALARM,ONAM=Open,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadCoils,R=SaveSafety_RBV,OFFSET=4,ZNAM=No,ZSV=NO_ALARM,ONAM=Yes,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadCoils,R=BigEndian_RBV,OFFSET=28,ZNAM=Little,ZSV=NO_ALARM,ONAM=Big,OSV=NO_ALARM,SCAN=\"I/O Intr\"")

# Write 31 bits starting at address 0. Function code=5. Default data type=UINT16
drvModbusAsynConfigure("$(VINDUM_PORT)_WriteCoils", "$(VINDUM_PORT)", 1, 5, 0, 31, UINT16, $(VPOLL_MS), "Vindum")
# Expanded from epics-modules/SyringePump/SPApp/Db/VindumWriteCoils.substitutions
# --- file "$(MODBUS)/db/bo_bit.template" --- (27 rows)
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:FillValve,OFFSET=0,ZNAM=Close,ONAM=Open")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:DeliverValve,OFFSET=1,ZNAM=Close,ONAM=Open")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:FillValve,OFFSET=2,ZNAM=Close,ONAM=Open")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:DeliverValve,OFFSET=3,ZNAM=Close,ONAM=Open")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=SaveSafety,OFFSET=4,ZNAM=No,ONAM=Yes")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:StartVolume,OFFSET=9,ZNAM=Done,ONAM=Start")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:StartAutoVolume,OFFSET=10,ZNAM=Done,ONAM=Start")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:StartVolume,OFFSET=11,ZNAM=Done,ONAM=Start")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:StartAutoVolume,OFFSET=12,ZNAM=Done,ONAM=Start")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:ZeroPressure,OFFSET=13,ZNAM=Done,ONAM=Zero")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:ZeroPressure,OFFSET=14,ZNAM=Done,ONAM=Zero")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:Start,OFFSET=15,ZNAM=Done,ONAM=Start")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:StartAuto,OFFSET=16,ZNAM=Done,ONAM=Start")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:Start,OFFSET=17,ZNAM=Done,ONAM=Start")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:StartAuto,OFFSET=18,ZNAM=Done,ONAM=Start")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:Stop,OFFSET=19,ZNAM=Done,ONAM=Stop")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:Stop,OFFSET=20,ZNAM=Done,ONAM=Stop")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=BothStop,OFFSET=21,ZNAM=Done,ONAM=Stop")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:ResetVolume,OFFSET=22,ZNAM=Done,ONAM=Reset")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:ResetVolume,OFFSET=23,ZNAM=Done,ONAM=Reset")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=ResetTotalVolume,OFFSET=24,ZNAM=Done,ONAM=Reset")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=ResetAllVolume,OFFSET=25,ZNAM=Done,ONAM=Reset")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=A:ResetCumulVol,OFFSET=26,ZNAM=Done,ONAM=Reset")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=B:ResetCumulVol,OFFSET=27,ZNAM=Done,ONAM=Reset")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=BigEndian,OFFSET=28,ZNAM=Little,ONAM=Big")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=ExitModbusMode,OFFSET=29,ZNAM=Done,ONAM=Exit")
dbLoadRecords("db/bo_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteCoils,R=ClearLatchedErrors,OFFSET=30,ZNAM=Done,ONAM=Clear")

# Read 6 bits starting at address 0. Function code=2. Default data type=UINT16
drvModbusAsynConfigure("$(VINDUM_PORT)_ReadContacts", "$(VINDUM_PORT)", 1, 2, 0, 6, UINT16, $(VPOLL_MS), "Vindum")
# Expanded from epics-modules/SyringePump/SPApp/Db/VindumReadContacts.substitutions
# --- file "$(MODBUS)/db/bi_bit.template" --- (6 rows)
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadContacts,R=A:Running,OFFSET=0,ZNAM=Stopped,ZSV=NO_ALARM,ONAM=Running,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadContacts,R=B:Running,OFFSET=1,ZNAM=Stopped,ZSV=NO_ALARM,ONAM=Running,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadContacts,R=A:Active,OFFSET=2,ZNAM=Idle,ZSV=NO_ALARM,ONAM=Active,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadContacts,R=B:Active,OFFSET=3,ZNAM=Idle,ZSV=NO_ALARM,ONAM=Active,OSV=MINOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadContacts,R=A:SafetyFlag,OFFSET=4,ZNAM=OK,ZSV=NO_ALARM,ONAM=Error,OSV=MAJOR,SCAN=\"I/O Intr\"")
dbLoadRecords("db/bi_bit.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadContacts,R=B:SafetyFlag,OFFSET=5,ZNAM=OK,ZSV=NO_ALARM,ONAM=Error,OSV=MAJOR,SCAN=\"I/O Intr\"")

# Read 42 16-bit analog input registers starting at 0. Function code=4. Default data type=UINT16
drvModbusAsynConfigure("$(VINDUM_PORT)_ReadInputRegs", "$(VINDUM_PORT)", 1, 4, 0, 42, UINT16, $(VPOLL_MS), "Vindum")
# Expanded from epics-modules/SyringePump/SPApp/Db/VindumReadInputRegisters.substitutions
# --- file "$(MODBUS)/db/longinInt32.template" --- (10 rows)
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=ComResponse,OFFSET=0,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=PumpType,OFFSET=19,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=A:ErrorState,OFFSET=23,DATA_TYPE=UINT32_BE,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=B:ErrorState,OFFSET=25,DATA_TYPE=UINT32_BE,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=CommonErrorState,OFFSET=27,DATA_TYPE=UINT32_BE,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=A:LatchedErrorState,OFFSET=29,DATA_TYPE=UINT32_BE,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=B:LatchedErrorState,OFFSET=31,DATA_TYPE=UINT32_BE,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=LatchedCommonErrorState,OFFSET=33,DATA_TYPE=UINT32_BE,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=CommonErrorState2,OFFSET=39,DATA_TYPE=UINT32_BE,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=LatchedCommonErrorState2,OFFSET=41,DATA_TYPE=UINT32_BE,SCAN=\"I/O Intr\"")

# --- file "$(MODBUS)/db/ai.template" --- (2 rows)
dbLoadRecords("db/ai.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=A:Position,OFFSET=20,BITS=10,EGUL=0.,EGUF=160.,PREC=1,SCAN=\"I/O Intr\"")
dbLoadRecords("db/ai.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=B:Position,OFFSET=21,BITS=10,EGUL=0.,EGUF=160.,PREC=1,SCAN=\"I/O Intr\"")

# --- file "$(MODBUS)/db/aiFloat64.template" --- (11 rows)
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=A:Pressure,OFFSET=1,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=B:Pressure,OFFSET=3,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=PairedPressure,OFFSET=5,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=A:FlowRate,OFFSET=7,DATA_TYPE=FLOAT32_BE,PREC=3,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=B:FlowRate,OFFSET=9,DATA_TYPE=FLOAT32_BE,PREC=3,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=PairedRate,OFFSET=11,DATA_TYPE=FLOAT32_BE,PREC=3,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=A:Volume,OFFSET=13,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=B:Volume,OFFSET=15,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=TotalVolume,OFFSET=17,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=A:TotalVolume,OFFSET=35,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadInputRegs,R=B:TotalVolume,OFFSET=37,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")

# Read 46 16-bit holding registers starting at 0. Function code=3. Default data type=UINT16
drvModbusAsynConfigure("$(VINDUM_PORT)_ReadHoldingRegs", "$(VINDUM_PORT)", 1, 3, 0, 46, UINT16, $(VPOLL_MS), "Vindum")
# Expanded from epics-modules/SyringePump/SPApp/Db/VindumReadHoldingRegisters.substitutions
# --- file "$(MODBUS)/db/longinInt32.template" --- (12 rows)
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:PumpModeRaw_RBV,OFFSET=2,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:PumpModeRaw_RBV,OFFSET=3,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=ServerID_RBV,OFFSET=31,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=AutoRateReturnTime_RBV,OFFSET=37,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:OpenDiffGain_RBV,OFFSET=38,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:CloseDiffGain_RBV,OFFSET=39,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:OpenPropGain_RBV,OFFSET=40,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:ClosePropGain_RBV,OFFSET=41,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:OpenDiffGain_RBV,OFFSET=42,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:CloseDiffGain_RBV,OFFSET=43,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:OpenPropGain_RBV,OFFSET=44,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")
dbLoadRecords("db/longinInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:ClosePropGain_RBV,OFFSET=45,DATA_TYPE=UINT16,SCAN=\"I/O Intr\"")

# --- file "$(MODBUS)/db/mbbi.template" --- (4 rows)
dbLoadRecords("db/vindumMbbi.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:Direction_RBV,OFFSET=0,ZRST=Extending,ZRVL=1,ONST=Retracting,ONVL=2,TWST=,TWVL=0,THST=,THVL=0,SCAN=\"I/O Intr\"")
dbLoadRecords("db/vindumMbbi.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:Direction_RBV,OFFSET=1,ZRST=Extending,ZRVL=1,ONST=Retracting,ONVL=2,TWST=,TWVL=0,THST=,THVL=0,SCAN=\"I/O Intr\"")
dbLoadRecords("db/vindumMbbi.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=PressureUnits_RBV,OFFSET=29,ZRST=PSI,ZRVL=0,ONST=bar,ONVL=1,TWST=kPa,TWVL=2,THST=MPa,THVL=3,SCAN=\"I/O Intr\"")
dbLoadRecords("db/vindumMbbi.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=RateUnits_RBV,OFFSET=30,ZRST=ml/min,ZRVL=0,ONST=ml/hour,ONVL=1,TWST=,TWVL=0,THST=,THVL=0,SCAN=\"I/O Intr\"")

# --- file "$(MODBUS)/db/aiFloat64.template" --- (14 rows)
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:SetFlowRate_RBV,OFFSET=5,DATA_TYPE=FLOAT32_BE,PREC=3,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:SetFlowRate_RBV,OFFSET=7,DATA_TYPE=FLOAT32_BE,PREC=3,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=SetMaxRate_RBV,OFFSET=9,DATA_TYPE=FLOAT32_BE,PREC=3,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:SetPressure_RBV,OFFSET=11,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:SetPressure_RBV,OFFSET=13,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=SetMaxPressure_RBV,OFFSET=15,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:PressureGain_RBV,OFFSET=17,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:PressureGain_RBV,OFFSET=19,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:SafetyPressure_RBV,OFFSET=21,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:SafetyPressure_RBV,OFFSET=23,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=A:SetVolume_RBV,OFFSET=25,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:SetVolume_RBV,OFFSET=27,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:FillOpenPressure_RBV,OFFSET=33,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")
dbLoadRecords("db/aiFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_ReadHoldingRegs,R=B:ReturnRateMult_RBV,OFFSET=35,DATA_TYPE=FLOAT32_BE,PREC=2,SCAN=\"I/O Intr\"")

# Write 46 16-bit holding registers starting at 0. Function code=16. Default data type=UINT16
drvModbusAsynConfigure("$(VINDUM_PORT)_WriteHoldingRegs", "$(VINDUM_PORT)", 1, 16, 0, 46, UINT16, $(VPOLL_MS), "Vindum")
# Expanded from epics-modules/SyringePump/SPApp/Db/VindumWriteHoldingRegisters.substitutions
# --- file "$(MODBUS)/db/longoutInt32.template" --- (12 rows)
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:PumpModeRaw,OFFSET=2,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:PumpModeRaw,OFFSET=3,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=ServerID,OFFSET=31,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=AutoRateReturnTime,OFFSET=37,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:OpenDiffGain,OFFSET=38,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:CloseDiffGain,OFFSET=39,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:OpenPropGain,OFFSET=40,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:ClosePropGain,OFFSET=41,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:OpenDiffGain,OFFSET=42,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:CloseDiffGain,OFFSET=43,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:OpenPropGain,OFFSET=44,DATA_TYPE=UINT16,PINI=NO")
dbLoadRecords("db/longoutInt32.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:ClosePropGain,OFFSET=45,DATA_TYPE=UINT16,PINI=NO")

# --- file "$(MODBUS)/db/mbbo.template" --- (4 rows)
dbLoadRecords("db/vindumMbbo.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:Direction,OFFSET=0,ZRST=Extending,ZRVL=1,ONST=Retracting,ONVL=2,TWST=,TWVL=0,THST=,THVL=0,PINI=NO")
dbLoadRecords("db/vindumMbbo.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:Direction,OFFSET=1,ZRST=Extending,ZRVL=1,ONST=Retracting,ONVL=2,TWST=,TWVL=0,THST=,THVL=0,PINI=NO")
dbLoadRecords("db/vindumMbbo.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=PressureUnits,OFFSET=29,ZRST=PSI,ZRVL=0,ONST=bar,ONVL=1,TWST=kPa,TWVL=2,THST=MPa,THVL=3,PINI=NO")
dbLoadRecords("db/vindumMbbo.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=RateUnits,OFFSET=30,ZRST=ml/min,ZRVL=0,ONST=ml/hour,ONVL=1,TWST=,TWVL=0,THST=,THVL=0,PINI=NO")

# --- file "$(MODBUS)/db/aoFloat64.template" --- (14 rows)
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:SetFlowRate,OFFSET=5,DATA_TYPE=FLOAT32_BE,PREC=3,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:SetFlowRate,OFFSET=7,DATA_TYPE=FLOAT32_BE,PREC=3,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=SetMaxRate,OFFSET=9,DATA_TYPE=FLOAT32_BE,PREC=3,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:SetPressure,OFFSET=11,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:SetPressure,OFFSET=13,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=SetMaxPressure,OFFSET=15,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:PressureGain,OFFSET=17,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=NO")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:PressureGain,OFFSET=19,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=NO")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:SafetyPressure,OFFSET=21,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:SafetyPressure,OFFSET=23,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=A:SetVolume,OFFSET=25,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=B:SetVolume,OFFSET=27,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=YES")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=FillOpenPressure,OFFSET=33,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=NO")
dbLoadRecords("db/aoFloat64.template", "P=$(VPREFIX),PORT=$(VINDUM_PORT)_WriteHoldingRegs,R=ReturnRateMult,OFFSET=35,DATA_TYPE=FLOAT32_BE,PREC=2,PINI=NO")

dbLoadRecords("db/VindumController.template", "P=$(VPREFIX), PORT=$(VINDUM_PORT)")
dbLoadRecords("db/VindumPumpN.template", "P=$(VPREFIX), PORT=$(VINDUM_PORT), PUMP=A:")
dbLoadRecords("db/VindumPumpN.template", "P=$(VPREFIX), PORT=$(VINDUM_PORT), PUMP=B:")

###############################################################################
iocInit()
###############################################################################
